COLOR=	color.o colordat.o hsl.o main.o

.c.o:
	lc1 -iINCLUDE: $*
	lc2 -v $*

.asm.o:
	assem $*.asm -o $*.o -i dh0:amiga/include


color:	$(COLOR)
	blink FROM LIB:c.o $(COLOR) to color LIB LIB:amiga.lib LIB:lc.lib 


all:
	delete #?.o
	make


objects:	$(COLOR)


o:		$(COLOR)

