
               Parts List For WinUAE Games Port A-D Converter.
               -----------------------------------------------

  Initial Test Parts List:-
  -------------------------

  1) R1...........................  1 KilOhm, 1/8 Watt Resistor.
  2) R2, R5, R7 & R8..............  10 KilOhm, 1/8 Watt Resistor.
  3) R3...........................  150 KilOhm, 1/8 Watt Resistor.
  4) R4...........................  220 KilOhm, 1/8 Watt Resistor.
  5) R6 & R9......................  4.7 KilOhm, 1/8 Watt Resistor.
  6) C1...........................  10nF Capacitor.
  7) C2...........................  220nF Capacitor.
  8) C3...........................  100uF Electrolytic Capacitor.
  9) C4 & C6......................  22nF Capacitor.
 10) C5...........................  47nF Capacitor.
 11) D1, D2 & D3..................  1N4148 Silicon Diode.
 12) Q1 & Q2......................  BC108 Transistor.
 13) ZD1..........................  6.2 Volt Zener.
 14) IC1..........................  TLC549.
 15) IC2..........................  NE555.
 16) IC3..........................  4017.
 17) RVA..........................  10 KilOhm, (Test), Linear Potentiometer.
 18) Perforated Board.
 19) Terminal Pins.
 20) Coloured Wire.
 21) Terminal Blocks.
 22) Tinned Copper Wire.
 23) Small Plastic Box.
 24) 9 Way ~D~ Type Plug.
 25) ~D~ Type Cover To Suit.
 26) Sleeving As Required.

  Parts For The Finished Item:-
  -----------------------------

  1) R10..........................  22 KilOhm, 1/4 Watt Resistor.
  2) RV1..........................  2.2 KilOhm Preset Variable resistor.

----------------------------------------------------------------------------

  Notes:-
  -------

  1) All components can be sourced from any supplier.
  2) All tolerances are + or - 10%.
  3) Capacitor working voltages greater than 10 Volts.

----------------------------------------------------------------------------

    Mr Barry Walker,
    70 King George Road,
    Loughborough,
    Leicestershire,
    LE11 2PA,
    England.

    Email to:-

    wisecracker@tesco.net

    BYE.....

============================================================================
