XTEXT=  global.o main.o xtext.o xtextsup.o

.c.o:
	cc $(CFLAGS) +C +D +Iram:prosuite.pre +l $* -o $*.o

.asm.o:
	as $(AFLAGS) $* -o $*.o

xtext:	$(XTEXT)
	ln -w -o xtext +cdb $(XTEXT) -lm32 -lc32

include:
	cc +Hprosuite.pre :amiga/include/prosuite/prosuite.h
	copy prosuite.pre ram:prosuite.pre

all:
	make include
	delete #?.o
	make

objects:	$(XTEXT)

o:		$(XTEXT)

