                                                                    ..
                                                            ,oo.   o°°o
         . oooo .                                          ,o° Oo  oo oo
       ,oooooooooo .                                       °Oo oo.  °oo.
      ,oooo'  °Oooooooo .                              .    °Ooooo  O° Oo
     ,Oooo°       °OOOooooo .                          o.      °oo  O  oo
     Ooooo'            °OOOoooo .                      oo    .  Oo  Oo oo
     ooooo.                 °oooooo....                oo    `Ooo°  `°oo°
     oooooo                        °°:::... .  .  . . .ooo
     `ooooooo.                          ` ° ` ` `: :ooOOOOOo..
      `°ooooooo .                                      °oo°
        `°ioooooo .                                     ooo
            ^ooooooo.                         .o. ,uUu, °oo
              ^ooooooo.      oOo  .o. o..Oo  .O`O °Oo.   oo,
     °           ooooooo    oO°  .O`O °O. °O °OO°    °O  °oo
    oo             ooooooo  °Oo  °OO° `Oo  Oo`O.. `OOo°   oo,
   oooo              oooooo. °OO.oO..  °O. °O  °'  `°'    `oo
  °oooooo .            °oooo   °O' °'
  °ooooooooo .       . oooo'
     °oooooooooooooooooo °
         ° oooooooooo °                   SCEneST vs. Rage '98  "The EvenT"



           ù AstroideA ù Enlightenment ù Kangooroo(Impulse/Amiga) ù
                             + a mnoho dalsich +







                                = Kde a Kedy =

              1998. 3. jul (piatok) od 16:00 hodiny
              1998. 5. jul (nedela) do  9:00 hodiny rana.

                          Almássy Téri Szabadidôközpont
                         (1088 BUDAPEST Almássy tér 6.)

                 Najlahsie pristupne z namestia Blaha Lujza.

           Oddychove centrum  je jedno z najvacsich Budapestianskych a
         najlepsie znamych kulturnych centier. 4-poschodova budova bude
         otvorena (6500 m²) od prizemia az po vrchne poschodie spolu
         s bufetom (okrem bazena). Fajcenie a pitie alkoholickych napojov
         je povolene, ale nemozte si flase priniest na miesto konania party.



                                  = SuTaZe =



         þ Demo Compo:

       - maximalna velkost: 8 MB
       - maximalne rozlisenie: 640 x 480
       - ESC klavesa na exit z dema v ktoromkolvek okamihu
       - 100% VGA kompatibilita pre PC compo + VESA 3.0 (volitelne)
       - Mozne platformy:
                                       ù PC/DOS
                                       ù PC/Linux
                                       ù PC/Windows 95
                                       ù Amiga 060/50MHz

        þ 64K Intro Compo:

      - maximalna velkost: 65536 Bytov
      - maximalne rozlisenie: 640 x 480
      - intro NESMIE pouzivat patche pre Gravis Ultrasound
      - ESC klavesa na exit z dema v ktoromkolvek okamihu
      - 100% VGA kompatibilita pre PC compo + VESA 3.0 (volitelne)
      - Mozne platformy:
                                       ù PC/DOS
                                       ù Amiga 060/50MHz

         þ 4K Intro Compo:

       - maximalna velkost: 4096 Bytov
       - cas predvadzania je 5 minut, ale intro moze byt aj dlhsie
       - maximalne rozlisenie: 640 x 480
       - intro NESMIE pouzivat patche pre Gravis Ultrasound
       - ESC klavesa na exit z dema v ktoromkolvek okamihu
       - 100% VGA kompatibilita pre PC compo + VESA 3.0 (volitelne)
       - 1 coder moze sutazit iba s jedinym 4K introm
       - hudba je doporucena!
       - Mozne platformy:
                                       ù PC/DOS
                                       ù Amiga 060/50MHz


        þ 256 byte Intro Compo:

      - Maximalna velkost: 256 Bytes,
      - cas predvadzania: 2 minuty, ale intro moze byt aj dlhsie,
      - Maximalne rozlisenie: 640 x 480,
      - ESC klavesa na exit z dema v ktoromkolvek okamihu
      - 100% VGA kompatibilita pre PC compo + VESA 3.0 (volitelne)
      - 1 coder moze sutazit iba s jedinym 256 Byte introm
      - Mozne platformy:

                                        ù PC/DOS
                                        ù Amiga 060/50MHz

        þ C64 Demo Compo:

      - maximalna velkost: 2 diskety
      - cas predvadzania je 10 minut, ale demo moze byt aj dlhsie

        þ Graphics Compo:

      - maximalne rozlisenie je 640 x 480 v True Color mode
      - povolene su formaty: GIF, IFF/LBM, PCX, TGA
      - 1 grafik moze sutazit iba s jedinym obrazkom
      - obrazky mozu byt podpisane autorom
      - scannovane alebo prekreslovane obrazky budu diskvalifikovane
      - fazy kreslenia nemusia byt pripojene, ale ked budu chybat, a porota
        neuveri v autentickost obrazku, bude obrazok diskvalifikovany

        þ Trace Compo:

      - maximalne rozlisenie je 640 x 480 v True Color mode
      - povolene su formaty: GIF, IFF/LBM, PCX, JPG, TGA
      - 1 grafik moze sutazit iba s jedinym obrazkom
      - obrazky mozu byt podpisane autorom

        þ C64 Graphics Compo:

      - konvertovane a scannovane obrazky budu diskvalifikovane
      - 1 grafik moze sutazit iba s jedinym obrazkom

        þ Multichannel Music Compo:

      - maximalna velkost pre Amigu: 1 MB
      - na PC moze byt vacsia, ale uistite sa, aby na prehratie
        stacil GUS s 1MB
      - cas prehravania: 3 minuty, ale pesnicka moze byt aj dlhsia
      - povolene formaty:
                 ù PC: XM,IT,S3M
                 ù Amiga: Octamed Sound Studio, DigiBooster, MOD
      - prosim, uistite sa, ze masina na ktorej chcete aby sa va
        pesnicka prehrala je vyznacena na diskete (Amiga resp. P
        (aj ked disketa a format suborov to vlastne urcuju)
      - .IT a .S3M sa budu prehravat v Impulse Trackeri a Fast Tracker
        sa posuzie na prehratie .MOD-y a .XM-ka
      - 1 hudobnik moze sutazit iba s jedinou pesnickou

        þ 4 Channel Music Compo:

      - maximalna velkost: 1 MB
      - prehrava sa: 3 minuty, ale pesnicka moze byt aj dlhsia
      - povoleny format: MOD
      - prosim, uistite sa, ze masina na ktorej chcete aby sa vasa
        pesnicka prehrala je vyznacena na diskete (Amiga resp. PC)
      - ma PC sa pouzije Fast Tracker
      - 1 hudobnik moze sutazit iba s jedinou pesnickou

        þ 8K Music Compo:       (originalna Rage sutaz)

      - Maximalna velkost: 8 KB,
      - Cas prehravania: 2 minuty, ale pesnicka moze byt aj dlhsia,
      - .IT a .S3M sa budu prehravat v Impulse Trackeri a Fast Tracker
        sa posuzie na prehratie .MOD-y a .XM-ka
      - povolene formaty: XM,IT,S3M,
      - 1 hudobnik moze sutazit iba s jedinou pesnickou

        þ C64 Music Compo:

      - cas prehravania: 3 minuty
      - 1 hudobnik moze sutazit iba s jedinou pesnickou

        þ Wild Compo:

      - cas predvadzania: max. 15 minut, ale moze byt aj dlhsie
      - mozu sutazit vsetky druhy vytvorov a platform
      - ak nesutazite s VHS videom, potom reprezentant vasej
        skupiny by mal kontaktovat organizatorov 15 minut pred
        sutazou (Vasa masina bude pripojena na projektor)

        þ Lamer Demo Compo:  (Originalna SCEneST sutaz)

      - doporucena velkost: > 20 MB,
      - cas predvadzania: 10 minut
      - 100% VGA kompatibilita pre PC
      - MUSI byt podpora Gravis Ultrasoundu
      - bude pustena iba produkcia na vysokej urovni, nezavisle na
        pocte sutaziacich
      - Mozne platformy:
                                        ù C64
                                        ù PC/DOS
                                        ù PC/Linux
                                        ù PC/Windows 95
                                        ù Amiga 060/50MHz

        þ Fun Compo:

      - Sutaz pre skupinu 5 ludi,
      - Pocet skupin, ktore mozu sutazit je vymedzeny,
      - Kazdy zo skupiny by mal mal hovorit po anglicky na zakladnej urovni..

        þ Quake'98 Compo:

      - Spustu pravidiel a informacii o tejto sutazi mozete najdete v
        quake98 suboroch.

        þ WOP Compo [Vitaz Party]: (Originalna SCEneST/Rage Sutaz)

      - Od teraz by sme chceli udelovat cenu za najlepsiu skupinu party.
        Kazda skupina, ktora sutazi na party s hocicim (a nezabudla uviest
        jeho/jej meno vo FILE_ID.DIZ automaticky vstupuje do tejto sutaze.
        Vitazi kazdej sutaze dostanu nejake body (pozri tabulku dalej)
        a skupina, s najvacsim poctom bodov na konci party bude titulovana
        najvyssim ocenenim party: cenou "Vitazna skupina party". Vitaz
        dostane nejaku cenu, ale uznanie je ovela dolezitejsie nez vec :)
        Cielom tejto sutaze je vidiet sutazit skupinu nie iba v jednej alebo
        dvoch sutaziach, ale vo vsetkych a sutazit s produktami najvyssej
        kvality. Od teraz nebude najdolezitejsia iba sikovnost coderov,
        ale tiez aky mate zmysel pre humor (Fun Compo a Lamer Demo Compo :),
        pretoze je velmi dolezite stat sa najlepsou skupinou na scene. :)
        Sutaze pochopitelne nebudu bodovane rovankou hodnotou. (napr. vitaz
        demo compo nedostane rovanku vysku bodov, ako 3. miesto v music
        compo.) Ludia sutaziaci v niekolkych skupinach dostanu body iba
        za prvu skupinu spomenutu vo FILE_ID.DIZ.


                W.O.P. body:

        =====================================================
                                        #1:     #2:     #3:
        =====================================================
        ù Demo Compo:                   10       7       5
        ù C64 Demo Compo:               10       7       5
        ù 64K Intro Compo:               7       5       3
        ù Wild Compo:                    6       4       2
        ù Fun Compo:                     6       4       2
        ù Lamer Demo Compo:              6       4       2
        ù Grafika Compo:                 3       2       1
        ù Trace Compo:                   3       2       1
        ù C64 Grafika Compo:             3       2       1
        ù Multichannel Music Compo:      3       2       1
        ù 4 Channel Music Compo:         3       2       1
        ù C64 Music Compo:               3       2       1
        ù 4K Intro Compo:                3       2       1
        ù 256B Intro Compo:              2       -       -
        ù 8K Music Compo:                2       -       -
        ù Quake Compo:                   1       -       -
        =====================================================



                              = SuTaZNeSTRoJe =

        ù PC:  Pentium MMX 200 MHz, 32MB RAM, Riva 128 4Mb, GUS PnP 1MB

                  Operacne Systemy:

                ù MS-DOS 7.0, HIMEM.SYS, 500K free base memory
                ù Linux
                ù Windows 95 OSR2 / DirectX v5.0 (6.0 ha addig kijön)

        ù AMIGA: Amiga 060/50MHz, 16MB RAM.

        ù C64:  Commodore 64, Floppy drive, Action Replay MK VII.

                ù Stara alebo nova verzia SID moze byt zvolena



                                 = VSTuPNe =


        ù 999 HUF na tri dni,
        ù vstup pre dievcata je zdarma :-),
        ù Hlasovat mozete zaplatenim vstupneho.



                                  = DeaDLiNes =

        ù terminy na odovzdanie produktov su rozdelene do 2 skupin:
          piatok vecer a soboty obeda (v zavislosti na sutazi)
        ù Vzhladom k velkemu poctu sutaziacich v music, wild a C64 sutaziach
          sa budu tieto sutaze konat prvu noc, alebo v sobotu doobeda.
        ù Takto sa bude nieco diat v sobotu a vy nebudete musiet sediet
          pocas 10 hodinovej sutaze v sobotu vecer (ako sme zaznamenali
          u viacerych sutaziacich minuly rok)
        ù Chceli by sme poprosit kazdeho, kto si nie je isty/ista :) ze
          moze s jeho/jej prispevkom sutazit v spomenutych sutaziach, aby
          poslal/la prispevok po kamaratovi, za ucelom nezmeskania terminu
          odovzdania! (Zvycajne 3/4 navstevsnikov pride v piatok vecer, ale
          nejaki dojdu v sobotu - hovorime k vam :), takze nezmeskajte
          deadlajny... )


                              = Poplatok pre sutaze =

     ù Poplatok pre vsetky sutaze je disk, na ktorom je vasa praca.
     ù ak najdeme virus hocijakeho druhu, potom VSETKY vstupe sutaziaceho
       budu diskvalifikovane!
     ù vsetko, s cim sa sutazi bude kopirovane do sutaznej masiny.
       Organizator bude k dispozicii pri predvadzacej masine. V tomto case
       mozete skontrolovat, ze vasa praca sa uspesne dostala na nasu masinu.
       (Intra a dema mozu byt pustane inde.) Budeme aj tak potrebovat
       diskety (pre pripad virusov :). Ak disketa obsahuje vstupy do
       viacerych sutaze (napr. 64k intro a nejaku grafiku), potom to
       nezabudnite organizatorovi, ktory kopiroval vasu pracu, pripomenut,
       aby sa touto cestou vas vstup nestratil.
    ù  sutaziaci na PC by mali odovzdat svoje prace na 3.5 HD disketach a
       amigisti na 3.5 DD disketach. To je velmi dolezite pre organizovanie.
     ù Kazdy disk by mal obsahovat velmi dolezite info zodpovedajuce vstupu
       napr.: NAZOV/AUTOR/SKUPINA/SUTAZ.
     ù Kazdy produkt MUSI mat FILE_ID.DIZ, ktore by malo obsahovat
       nasledovne:
               - Nazov produktu,
               - Meno sutaziaceho,
               - Nazov skupiny,
               - V ktorej sutazi bude produkt sutazit,
               - Na ktorej party bol produkt uverejneny.
     ù Ak mate nejake dolezite informacie o vstupe, ktore by sme mali vediet,
       potom to napiste do suboru s nazvom FONTOS.!!! .



                           = PoRoTa a HLaSoVaNie =


     ù Predvyberova porota bude zostavena z clenov teamov ktore
       organizuju party, dalsi ludia v obmedzenom pocte (max, 10
       porotcov.)
     ù Iba ludia ktori nesutazia v zodpovedajucej sutazi mozu byt
       clenom poroty tejto sutaze.
     ù Porota bude hodnotit sutazne prace stupnicou 1 az 10,
       prace ktore dostanu najviac bodov budu sutazit v sutaziach.
     ù Pocet sutaziacich zavisi od sutaze k sutazi.
     ù Za prace ktore prejdu predvyberovou porotou do sutaze sa
       bude hlasovat systemom 5 - 3 - 1 bodov v zavislosti od
       miesta ktore im hlasujuci daju.


                                   = CeNy =

        ù Tak ako minuly rok, snazime sa vymedzit celkovu sumu cien
          na 500000 HUF, ktore zahrnaju hotovost, hardware, software
          a ine.
        ù Snazime sa dat zodpovedajucu vysku cien pre vitaza kazdej
          sutaze, a mame na pamati kvalitu a kvantitu sutaze pri
          stanovovani vysky vyhry. Ale prosim nezabudajte kolko sutazi
          a kolko cien je na partym kebo tolkymi sposobmi musime ceny
          rozdelit.
        ù Hlavna udalost party - Demo Compo je vynimka, iba hardware a
          hotovost bude udelovane v nasledujucich hodnotach:

                                ù #1 50.000 HUF
                                ù #2 30.000 HUF
                                ù #3 20.000 HUF


          Samozrejme, tieto ciastky su symbolicke v porovnani s pracou a
          usilim, ktore boli do dema dane. Dufame, ze sutazivy duch bude
          hrat rozhodujucu rolu, pretoze vyhra na SCEneST/Rage party je
          NAJVACSIA cena na madarskej scene, nakolko je to "Udalost" roka :-)


                               = PoDaKoVaNia =

     Chceli by sme podakovat nasledujucim ludom za pomoc pri organizovani
                          SCEneST/Rage "The Event" :

        Reptile, TDMR, Lord, Kunci, MRZ, TSC, O-Man, René, Genesis, Egzo,
        Periwinkle, Alan, Gabriel, Kal, Beast, Edhellon, EFT, Trajic, SLO,
        Tilt, Norby, Soldier, True, Snowman, Laky, Ionic, Splash, Hawai,
        Cyd, Zool, Boldi, D-Lee, Ani, G. Miki, Narn, RNC, Brian, Albino,
        Dani, Myrel, Tom, Adi, NetPlayer a zahranicnym :) Johnko, REM 
        & XCene. 10x!

      A sponzorom party:

                                ù Telnet Magyarország
                                ù HumanSoft Games Rt
                                ù Woodstone Interactive
                                ù Pixel Graphics
                                ù Grafix SHS
                                ù PilotComp
                                ù ZED Magazin
                                ù Chip Magazin
                                ù CD Ultra
                                ù DNN Computer
                                ù Automex Kft
                                ù PC-X Magazin
                                ù PC Guru
                                ù 4M Computerbontó

                            Vdaka za vasu podporu!



                                 = PoZVaNie =

             Organizatori si dovoluju privitat kazdeho, specialne
                            nasledujuce skupiny:

        Exact Exhumers United Force Mortal Compact Hooligans Crew CaPaNÑa
        Unique PC Kangooroo Animals Murmidones D-Eyes Enlightenment Faculty
        ByTeam Promise Home Entertainment Silicon Brain Therapy Mandula
        Resource NicoTeam Tafundekli Design Renegades Immortal Rat Axioma
        Anarchy Budhaz Euthanasia Pulse Urinate Controlled Dreams Dinasty
        Majic 12 Neutron Contract Exceed Abaddon Agressive Giants Fresh
        Black Rainbow Dilemma Procreation Mist Emperor Virtual Imagines
        Remal Code & Light Sorcerers Inquisition CDI The Next Generation Team
        Brainsucked Crew A.L.L. Chrome The Mad Team Gravity Hydrogen Fiction
        Criminal Gang Darkside Quad Caterpillar Thitanium BaCTeRia Coma
        Chromance Frame 18 Amiga Only Profik ÅVH Iris Rhyme Firg Zsír...



                                = iNFoRMaCie =

        ù Chceli by sme poprosit kazdeho, aby si doniesol predlzovacku
          so sebou!
        ù Prosim, neprichadzajte pred otvorenim party, lebo to skvele
          vyrusuje organizatorov
        ù Majte vzdy volnu zastrcku aby si ostatni mohli pripojit napajacie
          kable.
        ù Budte opatrni pri odpajani vasich napajacich kablov, lebo ak cely
          rad ma prud od vas, potom mozete pekne schytat jednu do nosa :)
          (Minuly rok to mnoho ludi nezrealizovalo :)
        ù Chceli by sme poprosit kazdeho, aby pocas sutazi vypol akykolvek
          zdroj zvuku! (pozn. translatora: nie je jasne, ci to plati aj pre
          Samaelov spev :)
        ù Kazdy  sutaziaci je uzrozumeny s tym, ze jeho prace budu
          po slavnostnom odovzdani cien rozsirene a zapisane na
          CD-ROM (bez narokov na honorar).
        ù Kazdy by si mal doniest spacak, aby mal nieco, v com by sa
          vyspal.
        ù Do "spalne" :) mozte vstupit iba vyzuti.
        ù Konzumovanie alkoholickych napojov :) a fajcenie je na mieste party
          povolene ale extremne ozrati ludia budu vyhodeni bezpecnostnou
          sluzbou (pozn. prekl.: vysoki 2.20 metra a su ozbrojeni... ;-)
        ù Taggeri budu okamzite vydani policii. (policia sa nachadza
          100 metrov od miesta konania party) "Skater homeboys" budu musiet
          ist kreslit po stenach (pozn. pr.: napr. domov :) domov.
        ù Pocas akcii budete informovani cez lokalny zvukovy system,
          informacie budu tiez na projektore.
        ù Na prizemi bude 24h informacny servis. Pracujeme na on-line
          (non stop) TV informacnej sieti... ktora by mohla tiez vysielat
          sutaze!
        ù Umiestnime velku inzertnu dosku pri vstupe, ktora moze byt pouzita
          na pisanie informacii a oznamov ("Hladame coderov!",
          "Blala, kde si?", "Som na druhom poschodi. - Lazur/PLS",
          etc.) (pozn. prekl.: Bol to iba preklad, Lazur v skutocnosti po
          slovensky nevie, verte mi! :)
        ù Nenechavajte vase veci bez dozoru! Organizatori nenesu ziadnu
          zodpovednost za zmiznute veci!
        ù Kazda sutazna praca by mala mat FILE_ID.DIZ pripojene.




                                  = KoNTaKT =

          ù E-MAIL:    scenest@telnet.hu

          ù IRC:       #demoscene, #astroidea, #pixel

          ù WWW:       http://d-eyes.jpte.hu/scenest/
                       http://www.telnet.hu/scenest98/

          ù HLAS:      +36-28-471167
                       +36-30-542707

          ù POSTA:        » MELAN «              » WARD «
                       Oravecz Richárd          Kiss Balázs
                        1221,BUDAPEST         2143,KISTARCSA
                    Kapisztrán utca 23/b      Zrínyi M. u. 2.
                           HUNGARY                HUNGARY






                                                                          sss
           ~"üs                                                          d$$'
   sS$$$$$$$$S"  ,dS$$$$$" sS$$$$$"  $$b    $$$P sS$$$$$P sS$$$$$$$P "üS$$$ü"~
  $$$$S         d$$"      d$$"       $$$b   $$" d$$"     $$$S         .$$P
  `ü?$$$$$$$Ss, $$$       $$$ssss    $$$$b  $P  $$$ssss   üS$$$ss    .$$P
          >$$$$ $$$       $$$        $$ "$$$P$  $$$          "ü$$$b  $$P
    ,sssss$$$SS ?$$bssss, ?$$bssss,"?$$   ?P$$  ?$$bssss, sssssd$$$ $$$
   d$$$SSSSSS²'  ü?SSSSSSk ü?SSSSSSk "$    "SS   ü?SSSSSSk ?SSSSSP" `"üSSs.
   W$b                                                                  "$$b
   `?$$$$$$$"                                                     "$$$$$$$P'
      "üS$$'  : : S C E n e S T  vs  R A G E '98  "The Event" : :  `$$Sü"
          "                                                         "





