V3.0

MOUSE on
FKEYS on
NUMKEYS on
POINTER on
INTERACTIVE on

EVENT Blanc
SOUND play "RAM:MOD.COME FROM THE SKY" volume 64 pan 0 period 350 loops -1 fadein 2
BLANK 640 512 1 lace hires 0
PALETTE 000 fff
END

EVENT SOMMAIRE
PICTURE "RAM:SOMMAIRE"
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 8
BUTTON position 270 286 481 365  GOTO SOMMAIRETRAX
BUTTON position 76 174 293 252  GOTO SOMMAIREVISUELS
BUTTON position 79 396 292 475  GOTO SOMMAIREFLYERS
BUTTON position 455 172 670 252  GOTO SOMMAIREORIGINESok
BUTTON position 456 397 670 476  GOTO SOMMAIRETXT.C
PAUSE -1
END

EVENT SOMMAIREVISUELS
PICTURE "RAM:SOMMAIREVISUELS"
CYCLE on
TABS 148 248 348 448 548
MARGINS off 80 655
FONT ArtDeco.font 41 27
COLOR 14 17 17 17 17 14 14 17 0 14 14 13 22 24 14
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 24 3 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 102 60 ""
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
BUTTON position 145 92 192 112  GOTO TRANCE-FORM
BUTTON position 144 323 194 344  GOTO "WAKE UP !"
BUTTON position 146 209 194 229  GOTO "RAVIN' ON"
BUTTON position 144 438 194 463  GOTO FRACTALES
BUTTON position 590 471 685 495  GOTO SOMMAIRE
PAUSE -1
END

EVENT "WAKE UP !"
ANIM "RAM:WAKE UP !" 8 8
PAUSE 4
GOTO SOMMAIREVISUELS
END

EVENT TRANCE-FORM
ANIM "RAM:TRANCE-FORM" 10 3
PAUSE 3
GOTO SOMMAIREVISUELS
END

EVENT "RAVIN' ON"
ANIM "RAM:RAVIN' ON" 12 1
PAUSE 4
GOTO SOMMAIREVISUELS
END

EVENT FRACTALES
ANIM "RAM:FRACTALES" 6 8
PAUSE 4
GOTO SOMMAIREVISUELS
END

EVENT SOMMAIREFLYERS
PICTURE "RAM:SOMMAIREFLYERS"
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 8
BUTTON position 145 163 193 185  GOTO FLYER1
BUTTON position 143 370 193 393  GOTO FLYER2
BUTTON position 556 480 657 508  GOTO SOMMAIRE
BUTTON position 143 265 192 288  GOTO FLYERS.1
PAUSE -1
END

EVENT FLYER1
PICTURE "RAM:FLYER1"
PAUSE 5
GOTO SOMMAIREFLYERS
END

EVENT FLYER2
PICTURE "RAM:FLYER2"
PAUSE 4
GOTO SOMMAIREFLYERS
END

EVENT FLYERS.1
PICTURE "RAM:FLYERS.1"
MARK replace 1 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 0 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 0 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 0 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
SELECT replace 1 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 0 0 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 0 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
BUTTON position 604 484 629 512  GOTO FLYERS.2
PAUSE -1
END

EVENT FLYERS.2
PICTURE "RAM:FLYERS.2"
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 0 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 223 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 1 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 1 255
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 0 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 223 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
BUTTON position 599 -5 643 40  GOTO SOMMAIREFLYERS
PAUSE -1
END

EVENT SOMMAIRETRAX
PICTURE "RAM:SOMMAIRETRAX"
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
BUTTON position 144 230 193 253  GOTO HOUSE
BUTTON position 145 334 193 359  GOTO AMBIENT
BUTTON position 557 483 655 504  GOTO SOMMAIRE
BUTTON position 145 126 193 148  GOTO TECHNO
BUTTON position 146 441 194 462  GOTO HARDCORE
PAUSE -1
END

EVENT TECHNO
SOUND play "RAM:MOD.TECHNO" volume 64 pan 0 period 350 loops -1 fadein 2
BLANK 640 512 1 lace hires 0
PALETTE 000 fff
GOTO SOMMAIRETRAX
END

EVENT HOUSE
SOUND play "RAM:MOD.HOUSE" volume 64 pan 0 period 350 loops -1 fadein 5 fadeout 5
BLANK 640 512 1 lace hires 0
PALETTE 000 fff
GOTO SOMMAIRETRAX
END

EVENT AMBIENT
SOUND play "RAM:MOD.WARM NIGHT'N STARS" volume 64 pan 0 period 350 loops -1 fadein 2 fadeout 2
BLANK 640 512 4 lace hires 0
TABS 100 200 300 400 500
MARGINS off 32 607
PALETTE 000 fff ccc aaa 888 666 444 000 c00 d60 fb0 080 58b 53c a2b f3b
FONT ArtDeco.font 41 27
COLOR 1 7 7 7 7 0 1 7 0 1 2 3 5 4 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 24 3 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 ""
GOTO SOMMAIRETRAX
END

EVENT HARDCORE
SOUND play "RAM:MOD.BRAIN-DEAD-DAX" volume 64 pan 0 period 350 loops -1
BLANK 640 512 1 lace hires 0
PALETTE 000 fff
GOTO SOMMAIRETRAX
END

EVENT SOMMAIRETXT.C
PICTURE "RAM:SOMMAIRETXT.C"
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
BUTTON position 132 116 184 145  GOTO "ABOUT  TECHNOVISION ...                                         "
BUTTON position 133 170 183 198  GOTO CYBERGUIDE
BUTTON position 133 225 184 253  GOTO TECHNOCULTURE
BUTTON position 132 278 183 308  GOTO THECREAMDJs
BUTTON position 133 332 183 362  GOTO CODA.1
BUTTON position 133 386 183 414  GOTO CATALOGUED.PIXELS
BUTTON position 133 440 184 470  GOTO CREDITS
BUTTON position 606 470 706 491  GOTO SOMMAIRE
PAUSE -1
END

EVENT "ABOUT  TECHNOVISION ...                                         "
PICTURE "RAM:PAGE.CONTINUE"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 0 0 0 0 14 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "\t\\t\     ABOUT  TECHNOVISION ...                                         "
ATTRIBUTES kerning
TEXT 30 56 ""
TEXT 30 82 "Ce n° 6 de la collection D.PIXELS a pour ambition de"
TEXT 30 108 "présenter le mouvement techno en quelques octets !"
TEXT 30 134 "Le raver ou le Houseclubber initié n' y trouvera rien "
TEXT 30 160 "d' extraordinairement nouveau. "
TEXT 30 186 "Par contre, l' innocent humanoïde (inconscient des"
TEXT 30 212 "richesses fantastiques du monde merveilleux de la techno)"
TEXT 30 238 "pourra s' y faire une idée un peu plus précise du phénomène. "
TEXT 30 264 "De simples clics de souris (ou pressions du doigt pour la"
TEXT 30 290 "version écran tactile) sur les boutons de l 'interface vous"
TEXT 30 316 "permettent d' évoluer dans 5 rubriques."
TEXT 30 342 "La rubriques VISUELS vous propose 4 animations. "
TEXT 30 368 "La rubrique FLYERS vous offre 2 flyers libres de droit."
TEXT 30 394 "La rubrique TRAX propose un mini-panorama des principaux"
TEXT 30 420 "courants musicaux du mouvement techno. Vous pourrez y"
TEXT 30 446 "renouveller la bande-son de votre visite de TECHNOVISION"
TEXT 30 472 "(l' exit ne stoppe pas le morceau)."
TEXT 30 498 ""
TEXT 30 524 "  "
MARK replace 1 0
SELECT replace 1 0
BUTTON position 595 477 624 507  GOTO ABOUT2
PAUSE -1
END

EVENT ABOUT2
PICTURE "RAM:PAGE.EXIT"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 ""
ATTRIBUTES kerning
TEXT 30 56 "La rubrique ORIGINES vous donnera quelques indications"
TEXT 30 82 "sur les racines du mouvement techno."
TEXT 30 108 "Enfin, la rubrique TEXT.C (vous y êtes) aborde différents"
TEXT 30 134 "aspects de la culture techno."
TEXT 30 160 " \t\\t\\t\"
TEXT 30 186 ""
TEXT 30 212 ""
TEXT 30 238 "\t\\t\\t\                        Christian  DEZERT"
FONT diamond.font 12 20
STYLE 0 3 4 3 6 1 1 15 3 1 13 0 2 5 1 0 4 4 3
TEXT 30 264 "\t\\t\\t\      chridez@club-internet.fr"
MARK replace 1 0
SELECT replace 1 0
BUTTON position 588 469 631 511  GOTO SOMMAIRETXT.C
PAUSE -1
END

EVENT CYBERGUIDE
PICTURE "RAM:PAGE.CONTINUE"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "TECHNO :"
ATTRIBUTES kerning
TEXT 30 56 ""
TEXT 30 82 "Style musical apparu au milieu des années 80 en Grande-"
TEXT 30 108 "Bretagne."
TEXT 30 134 ""
TEXT 30 160 "La musique techno se caractérise par l'emploi massif de"
TEXT 30 186 "l'ordinateur pour générer des rythmes répétitifs et à"
TEXT 30 212 "consonnance électronique."
TEXT 30 238 ""
TEXT 30 264 "Parfois désignée comme \"\cyber-musique\"\, la musique"
TEXT 30 290 "techno a initié d'autres courants, qui sont parfois"
TEXT 30 316 "considérés à tort comme ses composantes : ambient"
TEXT 30 342 "garage, transe, hardcore, ..."
TEXT 30 368 ""
TEXT 30 394 "(In CYBERGUIDE deCyril FIEVET - Ed. Addison-Wesley)"
MARK replace 1 0
SELECT replace 1 0
BUTTON position 597 476 623 506  GOTO ILANA
PAUSE -1
END

EVENT ILANA
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 204 ""
TEXT 30 230 ""
TEXT 30 256 ""
TEXT 30 282 ""
TEXT 30 308 ""
TEXT 30 334 ""
TEXT 30 360 ""
TEXT 30 386 ""
TEXT 30 412 ""
TEXT 30 438 ""
TEXT 30 472 ""
ATTRIBUTES underline remap kerning
TEXT 33 32 "La techno est-elle une musique universelle ?"
ATTRIBUTES remap kerning
TEXT 33 58 "(Question posée par Univers Interactif à Ilana)"
TEXT 33 84 ""
ATTRIBUTES kerning
TEXT 33 102 "Bien sûr. Aucune musique n'est plus universelle que la"
ATTRIBUTES remap kerning
TEXT 33 128 "techno. Son absence de véritable langage et son émotion"
ATTRIBUTES kerning
TEXT 33 154 "fondée  exclusivement sur le rythme font danser les"
ATTRIBUTES remap kerning
TEXT 33 180 "foules de l'Australie au Brésil, sans problème de frontières"
TEXT 33 206 "ou de barrages culturels. Les machines qui la produisent"
TEXT 33 232 "sont de plus en plus faciles d'accès et d'utilisation."
TEXT 33 258 "Et l'énergie qui s'en dégage est la meilleure chaîne de"
TEXT 33 284 "communication qu'on puisse imaginer."
TEXT 33 310 "C'est une musique interactive et spontanée qui amène les"
TEXT 33 336 "gens à communiquer entre eux de manière très saine mais"
TEXT 33 362 "aussi à communiquer avec les éléments, avec la terre ..."
ATTRIBUTES kerning
TEXT 33 388 "Elle est au service de la danse et de l'esprit de transe"
ATTRIBUTES remap kerning
TEXT 33 414 "qu'on retrouve depuis toujours dans les rites du monde"
TEXT 41 84 ""
ATTRIBUTES kerning
TEXT 30 112 ""
ATTRIBUTES remap kerning
TEXT 515 161 ""
ATTRIBUTES kerning
TEXT 453 193 ""
ATTRIBUTES remap kerning
TEXT 484 219 ""
TEXT 33 441 "entier. En ce sens, elle est peut-être même éternelle ..."
ATTRIBUTES kerning
TEXT 33 475 "(in Univers INTERACTIF €#4  septembre  95) "
ATTRIBUTES remap kerning
TEXT 38 11 ""
TEXT 105 446 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO TELERAMA1
PAUSE -1
END

EVENT TELERAMA1
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 204 ""
TEXT 30 230 ""
TEXT 30 256 ""
TEXT 30 282 ""
TEXT 30 308 ""
TEXT 30 334 ""
TEXT 30 360 ""
TEXT 30 386 ""
TEXT 30 412 ""
TEXT 30 438 ""
TEXT 30 472 ""
ATTRIBUTES underline remap kerning
TEXT 33 32 "Entrez dans la dance :"
ATTRIBUTES remap kerning
TEXT 33 58 "Les branchés parlent aux français"
TEXT 33 84 ""
ATTRIBUTES kerning
TEXT 33 102 ""
ATTRIBUTES remap kerning
TEXT 33 128 "Quelle différence entre goa et zippy, hardcore et speedcore"
ATTRIBUTES kerning
TEXT 33 154 "hip hop et trip hop ? Est-il bien normal que le garage ne soit"
ATTRIBUTES remap kerning
TEXT 33 180 "pas dans la house, à l' orée de la jungle ? Pincez-nous, on "
TEXT 33 206 "rave ! Plus possible de faire la sourde oreille : la techno est"
TEXT 33 232 "parmi nous. Petit dico. Pour ne pas mourir idiot ..."
TEXT 33 258 "[...]"
TEXT 33 284 "HOUSE"
TEXT 33 310 "Aujourd' hui, elle fait partie des meubles. Courant majeur "
ATTRIBUTES kerning
TEXT 33 336 "de la dance music moderne, avec la techno, la house (dites"
ATTRIBUTES remap kerning
TEXT 33 362 "<<Ahouze>>) n' est nullement, malgré son nom, synonyme de"
TEXT 41 84 ""
TEXT 515 161 ""
ATTRIBUTES kerning
TEXT 453 193 ""
ATTRIBUTES remap kerning
TEXT 484 219 ""
TEXT 33 441 ""
ATTRIBUTES kerning
TEXT 33 475 ""
ATTRIBUTES remap kerning
TEXT 38 11 ""
TEXT 105 446 ""
TEXT 55 390 ""
TEXT 35 391 "<< fabriquée à la maison>>. Le terme vient d' un club de Chicago"
ATTRIBUTES kerning
TEXT 35 417 "le Warehouse (<<Entrepôt>>), où un disc-jokey nommé "
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO TELERAMA2
PAUSE -1
END

EVENT TELERAMA2
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 ""
ATTRIBUTES kerning
TEXT 33 58 "Frankie Knuckles popularisa, li y a plus de dix ans, l' art "
TEXT 33 84 "de juxtaposer musique noire et pop synthétique. Depuis"
TEXT 33 110 "notre maman house a fait des tas de petits : la deep house"
TEXT 33 136 "new-yorkaise, lente et mélodieuse ; la progressive house"
TEXT 33 162 "anglaise, pop et simpliste ou la gabber house hollandaise"
TEXT 33 188 "bruitiste et sautillante. La house ne s' use même pas si"
TEXT 33 214 "on en abuse."
TEXT 33 240 ""
TEXT 33 266 ""
TEXT 33 292 "\t\\t\\t\Philippe BARBOT"
TEXT 33 318 ""
TEXT 33 344 ""
TEXT 33 370 ""
TEXT 33 396 "(in Télérama 24 février  96)\t\\t\\t\"
TEXT 33 422 ""
TEXT 33 448 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO BEST
PAUSE -1
END

EVENT BEST
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 "L'interprétation des raves:"
ATTRIBUTES kerning
TEXT 33 58 ""
TEXT 33 84 "En trois ans d' existence anglaise, la House Music a évolué"
TEXT 33 110 "en Acid House, Techno-beat, New Beat, Rave Parties géantes"
TEXT 33 136 "et \"\festivals d'amour\"\. De mouvement musical en phénomène"
TEXT 33 162 "social, que l'on va jusqu'à débattre à la chambre des Lords"
TEXT 33 188 "toutes races, classes sociales, styles et éthiques confon-"
TEXT 33 214 "dues, l'hydre rythmique et son culte, la \"\rave party\"\ a tout"
TEXT 33 240 "digéré : l' anti-Thatcherisme, le Hooliganisme, les Skinheads"
TEXT 33 266 "la mode vestimentaire, a laissé quelques rides au rock, à la"
TEXT 33 292 "black music, en a assimilé ce qui lui semblait nécessaire, a"
TEXT 33 318 "changé le visage des salles de concerts et des clubs, enfin"
TEXT 33 344 "est devenu le phénomène le plus influent (et le plus vendeur)"
TEXT 33 370 "depuis l' ère punk Mais alors que l'euphorie a déja gagné la"
TEXT 33 396 "plupart des pays d' Europe, stupeur, d' un avis unanime, les"
TEXT 33 422 ""
TEXT 33 448 ""
TEXT 33 474 ""
ATTRIBUTES remap kerning
TEXT 34 52 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO BEST2
PAUSE -1
END

EVENT BEST2
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 ""
ATTRIBUTES kerning
TEXT 33 58 "Anglais déclarent le phénomène mort et enterré. Baste."
TEXT 33 84 "Serions-nous condamné à grignoter les restes d' un festin"
TEXT 33 110 "dévoré par d' autres ?  ..."
TEXT 33 136 ""
TEXT 33 162 ""
TEXT 33 188 ""
TEXT 33 214 "\t\\t\\t\Gilles RIBEROLLES"
TEXT 33 240 ""
TEXT 33 266 ""
TEXT 33 292 "(in BEST #267-octobre  90)"
TEXT 33 318 ""
TEXT 33 344 ""
TEXT 33 370 ""
TEXT 33 396 ""
TEXT 33 422 ""
TEXT 33 448 ""
TEXT 33 474 ""
TEXT 33 500 ""
ATTRIBUTES remap kerning
TEXT 34 52 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO BIENPUBLIC
PAUSE -1
END

EVENT BIENPUBLIC
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 "LES  CYBER-HEROS  DE  LA  VAGUE  TECHNO :"
ATTRIBUTES underline bold kerning
TEXT 33 58 ""
ATTRIBUTES kerning
TEXT 33 84 ""
TEXT 33 110 "Pour le non initié, la techno a plus à voir avec une compilation"
TEXT 33 136 "de sons bruts aux pulsations rythmées et contrôlées qui"
TEXT 33 162 "l' apparentent et la limitent à une transe initiatique."
TEXT 33 188 "Sacrilège ! Ces affirmations osées vous vaudront les foudres"
TEXT 33 214 "des inconditionnels pour qui cette nouvelle mode musicale"
TEXT 33 240 "en franchissant la frontière de l' \"\underground\"\ où elle était"
TEXT 33 266 "cantonnée, commence à revêtir les allures d' un authentique"
TEXT 33 292 "phénomène culturel. La techno a ses courants et ses rites"
TEXT 33 318 "sa mode vestimentaire et son vocabulaire, ses \"\maîtres de"
TEXT 33 344 "cérémonie\"\ et, surtout, cette autre façon de mettre en sons"
TEXT 33 370 "qui, pour la première fois sans doute dans l' univers de l'"
TEXT 33 396 "expression musicale, utilise des technologies nouvelles"
TEXT 33 422 "comme seul support de la création musicale."
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO BIENPUBLIC2
PAUSE -1
END

EVENT BIENPUBLIC2
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 ""
ATTRIBUTES kerning
TEXT 33 58 "Expression originale et catégorielle d' \"\une jeunesse d'"
TEXT 33 84 "aujourd' hui\"\ -les 15-25 ans pour le noyau dur -, la techno a"
TEXT 33 110 "bien sûr aussi ses points d' interrogation dont le moindre"
TEXT 33 136 "n' est pas celui de la drogue. Bête noire des organisateurs"
TEXT 33 162 "de soirées à large audience, elle infiltre un public qui sait y"
TEXT 33 188 "trouver un lieu propice à son usage et son commerce et"
TEXT 33 214 "pollue en même temps les vrais \"\pros\"\ pour qui la création"
TEXT 33 240 "et la recherche musicales sont les uniques motivations."
TEXT 33 266 "Aujourd' hui, la vague techno s' amplifie suivant les réseaux"
TEXT 33 292 "des nouveaux moyens de communication. Que se cache-t' il"
TEXT 33 318 "sous ses remous \"\new wave\"\ ? Enquête."
TEXT 33 344 ""
TEXT 33 370 "\t\\t\\t\Anne-Marie KAISER"
TEXT 33 396 ""
TEXT 33 422 "(in Le Bien Public  4  décembre  95)"
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO ARTPRESS
PAUSE -1
END

EVENT ARTPRESS
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 "TECHNO, DEATH METAL, HARDCORE :"
ATTRIBUTES kerning
TEXT 33 58 ""
TEXT 33 84 "...Le fonctionnement de la techno est assez similaire"
TEXT 33 110 "puisque le rapport frontal entre la star et son public"
TEXT 33 136 "disparaît. Les variations de fréquence et de décibels"
TEXT 33 162 "prennent le pas sur les démonstrations techniques, qu'"
TEXT 33 188 "elles soient instrumentales ou vocales. Aux chansons"
TEXT 33 214 "composées autour de deux accords qui offrent finalement"
TEXT 33 240 "peu de variations mélodiques, la techno propose l' autopsie"
TEXT 33 266 "de telle ou telle fréquence, la décomposition en informa-"
TEXT 33 292 "tions digitales d' une courbe sinusoïdale, le martèlement"
TEXT 33 318 "paroxystique du rythme. Le <<concert>> devient un gigan-"
TEXT 33 344 "tesque laboratoire sonore. Pour les DJ's, chaque expérience"
TEXT 33 370 "est différente de la précédente, la plupart d' entre eux ne"
TEXT 33 396 "voient pas l' interêt de figer leurs  compositions sur un CD."
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO ARTPRESS2
PAUSE -1
END

EVENT ARTPRESS2
PICTURE "RAM:PAGE.EXIT+continue"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 ""
ATTRIBUTES kerning
TEXT 33 58 "Se considérant comme de simples opérateurs, ils n' envisa-"
TEXT 33 84 "gent pas non plus de sortir de l' anonymat. D' où la position"
TEXT 33 110 "inconfortable des maisons de disques cherchant à commer-"
TEXT 33 136 "cialiser une musique dont l' essentiel de la production n' est"
TEXT 33 162 "pas enregistré. Comment faire émerger des individualités"
TEXT 33 188 "dans un mouvement qui refuse d' en reconnaître ? La seule"
TEXT 33 214 "solution, pour l' instant, consistant à sortir des dizaines de"
TEXT 33 240 "compilations regroupant des musiciens totalement inconnus"
TEXT 33 266 "disques dont la durée de vie ne dépasse pas le temps d' une"
TEXT 33 292 "campagne publicitaire."
TEXT 33 318 "\t\\t\\t\..."
TEXT 33 344 ""
TEXT 33 370 "\t\\t\\t\Olivier  WICKER"
TEXT 33 396 ""
TEXT 33 422 ""
TEXT 33 448 "      (in ART PRESS #211 mars 96)\t\\t\\t\"
TEXT 33 474 ""
MARK complement
SELECT replace 1 0
BUTTON position 596 466 622 494  GOTO SANSNOM
SELECT none
BUTTON position 10 470 41 487  GOTO SOMMAIRETXT.C
PAUSE -1
END

EVENT SANSNOM
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 "Extrait d' une Interview de Lenny Dee  par Debora Langer:"
ATTRIBUTES kerning
TEXT 33 58 ""
TEXT 33 84 "... Quand j' ai commencé à être DJ, je sortais et je n' écoutais"
TEXT 33 110 "que de la disco revampée. Toujours the same old song, la"
TEXT 33 136 "même structure, etc... Alors que la musique techno défie"
TEXT 33 162 "toute forme musicale existante, toute loi antérieure."
TEXT 33 188 "Aucun tracé préétabli, juste le son donnant la vibe, juste le"
TEXT 33 214 "rythme, pas de chanson... juste un DJ faisant passer quelque-"
TEXT 33 240 "chose aux gens. [...] La techno m' a mené au son, à l' énergie"
TEXT 33 266 "à une toute autre forme de pensée. Et quand j' ai commencé"
TEXT 33 292 "à faire des disques, sous un label new yorkais, j' ai été surpris"
TEXT 33 318 "par le fait qu' ils se vendaient quasi exclusivement en Europe."
TEXT 33 344 ""
TEXT 33 370 ""
TEXT 33 396 ""
TEXT 33 422 "(in SANS NOM #2 printemps 95)\t\\t\\t\"
TEXT 33 448 ""
TEXT 33 474 ""
TEXT 33 500 ""
TEXT 33 526 ""
TEXT 33 552 ""
TEXT 33 578 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO TEKNO-KEUFS
PAUSE -1
END

EVENT TEKNO-KEUFS
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 "NOTE D' INFORMATION DU MINISTERE DE L' INTERIEUR SUR LES "
ATTRIBUTES underline center kerning
TEXT 167 58 "SOIREES \"\RAVE\"\ OU \"\ACID HOUSE\"\"
ATTRIBUTES kerning
TEXT 33 84 ""
TEXT 33 110 "Originaire de Grande Bretagne, ce phénomène semble se"
TEXT 33 136 "développer en France très rapidement. Les soirées \"\RAVE\"\"
TEXT 33 162 "(signifiant rêves éveillés et hallucinatoires) généralement"
TEXT 33 188 "organisées dans des lieux publics tels que discothèques"
TEXT 33 214 "dancings, etc..., se différencient des soirées \"\ACID HOUSE\"\"
TEXT 33 240 "organisées dans des lieux \"\sauvages\"\ (usines désaffectées"
TEXT 33 266 "terrains vagues, péniches, etc...) par la drogue employée et"
TEXT 33 292 "la musique distribuée. Pour la première, on y emploie l'"
TEXT 33 318 "ecstasy sur de la \"\TECHNO MUSIC\"\. En ce qui concerne la"
TEXT 33 344 "seconde, les participants recherchent des effets beaucoup"
TEXT 33 370 "plus puissants, car ils usent de L.S.D. 25, en écoutant de la"
TEXT 33 396 "musique \"\ACID MUSIC\"\. Cette substance provoque de"
TEXT 33 422 "puissantes hallucinations, parfois agréables, parfois"
TEXT 33 448 "cauchemardesques qui peuvent mener à la folie, au suicide"
TEXT 33 474 "ou à des actes criminels. "
TEXT 33 500 ""
TEXT 33 526 ""
TEXT 33 552 ""
TEXT 33 578 ""
TEXT 33 604 ""
TEXT 33 630 ""
TEXT 33 656 ""
TEXT 33 682 ""
TEXT 33 708 ""
TEXT 33 734 ""
TEXT 33 760 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO TEKNO-KEUFS2
PAUSE -1
END

EVENT TEKNO-KEUFS2
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 ""
ATTRIBUTES kerning
TEXT 33 58 "Elles peuvent s' arrêter, et revenir quelques mois plus"
TEXT 33 84 "tard, même sans reprendre cette drogue entre temps."
TEXT 33 110 "Ces soirées sont fréquentées par une jeunesse de 20 à 30"
TEXT 33 136 "ans environ de tous milieux. Leurs lieux sont connus au "
TEXT 33 162 "dernier moment par le biais d' un serveur Minitel 3615 code"
TEXT 33 188 "RAVE. Les drogues sont distribuées par des revendeurs"
TEXT 33 214 "spécialement dépêchés pour l' occasion, généralement de"
TEXT 33 240 "Paris ou la région parisienne et qui souvent proposent une"
TEXT 33 266 "gamme complète (héroïne, cocaïne, cannabis, crack)"
TEXT 33 292 "fournissent à la demande. Devant les dangers évidents que"
TEXT 33 318 "représentent de telles manifestations, il importe de lutterµ"
TEXT 33 344 "efficacement contre celles-ci dès qu' on en a connaissance"
TEXT 33 370 "soit en les faisant interdire par arrêté préfectoral ou "
TEXT 33 396 "municipal, soit en informant l' organisateur qu' il est passible"
TEXT 33 422 "des peines figurant à l' art. L. 627 al. 5 ou de provoquer une"
TEXT 33 448 ""
TEXT 33 474 ""
TEXT 33 500 ""
TEXT 33 526 ""
TEXT 33 552 ""
TEXT 33 578 ""
TEXT 33 604 ""
TEXT 33 630 ""
TEXT 33 656 ""
TEXT 33 682 ""
TEXT 33 708 ""
TEXT 33 734 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO TEKNO-KEUFS3
PAUSE -1
END

EVENT TEKNO-KEUFS3
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 ""
ATTRIBUTES kerning
TEXT 33 58 "intervention directe sous contrôle de l' autorité judiciaire."
TEXT 33 84 ""
TEXT 33 110 ""
TEXT 33 136 "(in CODA  #10 (TEKNO KEUFS) Février  95)"
TEXT 33 162 ""
TEXT 33 188 ""
TEXT 33 214 ""
TEXT 33 240 ""
TEXT 33 266 ""
TEXT 33 292 ""
TEXT 33 318 ""
TEXT 33 344 ""
TEXT 33 370 ""
TEXT 33 396 ""
TEXT 33 422 ""
TEXT 33 448 ""
TEXT 33 474 ""
TEXT 33 500 ""
TEXT 33 526 ""
TEXT 33 552 ""
TEXT 33 578 ""
TEXT 33 604 ""
TEXT 33 630 ""
TEXT 33 656 ""
TEXT 33 682 ""
TEXT 33 708 ""
TEXT 33 734 ""
ATTRIBUTES underline remap kerning
TEXT 98 68 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO ACTUEL
PAUSE -1
END

EVENT ACTUEL
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 "RAVE : Les cathédrales d' une fête qui n' en finit plus :"
ATTRIBUTES kerning
TEXT 33 58 ""
TEXT 33 84 "Après le sida, les virus informatiques, les guerres tribales"
TEXT 33 110 "et la crise mondiale exponentielle, la rave serait-elle la"
TEXT 33 136 "nouvelle épidémie de cette fin de siècle, infection festive"
TEXT 33 162 "et joyeuse, pour gommer la grisaille contemporaine ?"
TEXT 33 188 "Depuis ses débuts dans les clubs \"\undergrounds\"\ de"
TEXT 33 214 "Chicago et d' Ibiza, une musique nouvelle se répand par"
TEXT 33 240 "les voyages, les échanges et les réseaux : ce sont de jeunes"
TEXT 33 266 "Anglais, venus par charters en vacances à Ibiza, qui"
TEXT 33 292 "ramenèrent dans leurs bagages les disques et les cassettes"
TEXT 33 318 "de DJs. Nous sommes en 1988. Ces vacanciers sont à l'"
TEXT 33 344 "origine des premiers clubs d' \"\acid house\"\ anglais."
TEXT 33 370 "L' interdiction de ceux-ci par Thatcher provoquera la"
TEXT 33 396 "mutation des clubs vers la rave : la fête à dix mille"
TEXT 33 422 ""
TEXT 33 448 ""
TEXT 33 474 ""
TEXT 33 500 ""
TEXT 33 526 ""
TEXT 33 552 ""
TEXT 33 578 ""
TEXT 33 604 ""
TEXT 33 630 ""
TEXT 33 656 ""
TEXT 33 682 ""
TEXT 33 708 ""
ATTRIBUTES underline remap kerning
TEXT 98 68 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO ACTUEL2
PAUSE -1
END

EVENT ACTUEL2
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 33 32 ""
ATTRIBUTES kerning
TEXT 33 58 "énorme, révolte pacifique, la transe d' une génération"
TEXT 33 84 "contre les interdits policiers."
TEXT 33 110 "\t\\t\                    ..."
TEXT 33 136 ""
TEXT 33 162 ""
TEXT 33 188 "\t\\t\      Vincent  BOREL"
TEXT 33 214 ""
TEXT 33 240 ""
TEXT 33 266 ""
TEXT 33 292 "(in ACTUEL Avril  93)"
TEXT 33 318 ""
TEXT 33 344 ""
TEXT 33 370 ""
TEXT 33 396 ""
TEXT 33 422 ""
TEXT 33 448 ""
TEXT 33 474 ""
TEXT 33 500 ""
TEXT 33 526 ""
TEXT 33 552 ""
TEXT 33 578 ""
TEXT 33 604 ""
TEXT 33 630 "utation des clubs vers la rave : la fête à dix mille"
TEXT 33 656 ""
TEXT 33 682 ""
TEXT 33 708 ""
TEXT 33 734 ""
TEXT 33 760 ""
TEXT 33 786 ""
TEXT 33 812 ""
TEXT 33 838 ""
TEXT 33 864 ""
TEXT 33 890 ""
TEXT 33 916 ""
TEXT 33 942 ""
ATTRIBUTES underline remap kerning
TEXT 98 68 ""
TEXT 32 125 ""
MARK complement
SELECT replace 1 0
BUTTON position 597 477 623 505  GOTO CLONE.PAGE1
PAUSE -1
END

EVENT CLONE.PAGE1
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "ALORS, TECH NO FUTURE ?"
ATTRIBUTES remap kerning
TEXT 30 56 ""
TEXT 30 82 "Qui aime franchir le mur du son et graviter en orbite "
TEXT 30 108 "techno se téléporte jusqu'au trou noir, glissant vers un "
TEXT 30 134 "coin perdu, une industrie désaffectée, des souterrains...  "
TEXT 30 160 "A cette déviation géographique pour un lieu râvé (qui ne "
TEXT 30 186 "sera pas Bercy et son Dance Machin), s'associe le "
TEXT 30 212 "décalage temporel, cet intervalle flou avant que le "
TEXT 30 238 "crépuscule embrasse l'aurore."
TEXT 30 264 "Dans ce laps de temps, la techno est toute en démesure si "
TEXT 30 290 "l'on excepte ses initiales codées : BPM (Beat Per Minute) "
TEXT 30 316 "qui autant que l'on s'en souvienne prennent plutôt les "
TEXT 30 342 "jambes avant la tête. Répétitive, nappée, la techno puise "
TEXT 30 368 "aux ressources synthétiques, stéréopanoramiques. Plus "
TEXT 30 394 "on s'en abreuve par vice déviant et mieux s'élimine "
TEXT 30 420 "l'adipeux, voire le vague à l'âme, l'ombre au tableau. La "
TEXT 30 446 "danse, la fiesta n'est pourtant pas tout. La techno c'est"
MARK complement
SELECT replace 1 0
BUTTON position 596 476 624 505  GOTO CLONE.PAGE2
PAUSE -1
GOTO CLONE.PAGE2
END

EVENT CLONE.PAGE2
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "d'abord un espace-temps musical ouvert en grand. Il peut "
TEXT 30 56 "tanguer entre le hardcore machinal, givré et l'ambient "
TEXT 30 82 "céleste, évaporée d'une transe fièvreuse et envôutante. "
TEXT 30 108 "Sans compter, on peut ainsi se dépenser corps et âme "
TEXT 30 134 "pour la techno, comme guidé par une intuition lactée qui"
TEXT 30 160 "va la nuit entière du sombre au clair de l'arrosé matinal. "
TEXT 30 186 "Un parcours virtuel en somme."
TEXT 30 212 "La communion de masse qui caractérise les raves "
TEXT 30 238 "agglutinées a certes un accent de 70's, ce même gôut "
TEXT 30 264 "pour l'excès et un plaisir en marge pour des illusions "
TEXT 30 290 "neuves. Mais si l'ectasy a succédé ou complèté le LSD, "
TEXT 30 316 "que les fleurs popcolor ont muté en fractales, la musique "
TEXT 30 342 "techno décolle bien au-delà des idées planantes d'un "
TEXT 30 368 "Woodstock chevelu. Elle se nourrit librement quoiqu'en "
TEXT 30 394 "plus effervescent de la house et du disco son ancêtre aux "
TEXT 30 420 "boules à facettes. Elle capte aussi de l'électro du Nord, le "
TEXT 30 446 "son belge encore plus dépouillé. Elle ose enfin vers des "
TEXT 30 472 ""
MARK complement
SELECT replace 1 0
BUTTON position 595 477 623 503  GOTO CLONE.PAGE3
PAUSE -1
GOTO CLONE.PAGE3
END

EVENT CLONE.PAGE3
PICTURE "RAM:PAGE.EXIT"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
WORDWRAP off
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "sessions tribales jusqu'au beat le plus primitif, voire flirte"
ATTRIBUTES kerning
TEXT 30 56 "avec la tradition d'une castagnette ou d'un biniou. Les "
ATTRIBUTES remap kerning
TEXT 30 82 "artisans de la techno s'apparentent ainsi à des sorciers, "
TEXT 30 108 "musiciens et/ou DJ's, qui, les mains dans le numérique ou "
TEXT 30 134 "le vinyl pétrissent le son du futur. A échantillonner tout ce "
TEXT 30 160 "que la nature musicale lui offre, la techno compile et "
TEXT 30 186 "diffuse au delà des frontières."
TEXT 30 212 ""
TEXT 30 238 "(in CLONE  #0  aout 94)"
TEXT 30 264 ""
TEXT 30 290 ""
TEXT 30 316 ""
TEXT 30 342 ""
TEXT 30 368 ""
TEXT 30 394 ""
TEXT 30 420 ""
TEXT 30 446 ""
TEXT 30 472 ""
TEXT 30 498 ""
MARK replace 0 1
SELECT replace 1 0
BUTTON position 596 476 623 505  GOTO SOMMAIRETXT.C
PAUSE -1
GOTO ILANA
END

EVENT TECHNOCULTURE
PICTURE "RAM:PAGE.CONTINUE"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 2 75 "LIVRES :     - Localizer 1.0 :  la culture  techno en 300 pages quadri. "
TEXT 2 101 " \t\  Distr. IN/OUT."
TEXT 2 127 "\t\- What Kind of House party is this ? MIY publishing."
TEXT 2 153 "\t\- House Nation Book : tous les contacts de la techno"
TEXT 2 179 "\t\   mondiale. Distr. CODA."
TEXT 3 181 "\t\"
TEXT 3 207 "\t\- Scribe Tribe : livre consacré aux flyers."
TEXT 94 209 "    "
TEXT 94 235 "\t\   Ed. JAM BOOKS."
TEXT 3 237 "\t\"
TEXT 3 263 "\t\- E comme Ecstasy de Nicholas Saunders"
TEXT 3 289 "\t\   Ed. du LEZARD. \t\"
TEXT 3 315 "\t\- Digraphe n° 68 : revue littéraire proposant un "
TEXT 3 341 "\t\   dossier techno. Ed. MERCURE DE FRANCE."
TEXT 3 367 "\t\- Highflyers clubravepartyart.Distr. REACTIVE."
TEXT 4 299 ""
TEXT 3 334 ""
TEXT 3 360 ""
TEXT 3 386 ""
TEXT 3 412 "MAGAZINES : CODA, PLAY, REMIX, ZIPPER, OUT SOON, FRONTPAGE "
TEXT 3 438 "\t\       DJ, MIXMAG,MUSIK, JOCKEYSLUT, ORDINATEURS &"
TEXT 4 377 ""
TEXT 4 403 ""
TEXT 4 429 ""
TEXT 3 465 "\t\       MUSIQUE Hors Série"
FONT Compact.font 25 31
ATTRIBUTES center kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXT 197 16 "T E C H N O C U L T U R E"
FONT Compact.font 19 24
ATTRIBUTES kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 5 343 ""
MARK complement
SELECT replace 1 0
BUTTON position 596 476 623 506  GOTO TECHNOCULTURE.2
PAUSE -1
END

EVENT TECHNOCULTURE.2
PICTURE "RAM:PAGE.EXIT"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "TV :   -CHILL OUT ZONE/PARTY ZONE (MTV)"
ATTRIBUTES kerning
TEXT 30 56 ""
TEXT 30 82 "CD ROM :       -MEET MEDIA BAND (Canter  Technology)"
TEXT 24 68 "\t\          "
TEXT 24 94 ""
TEXT 24 120 "\t\          -HEADTRAVEL (Man Made Media/Moonshine Music)   "
TEXT 24 146 "  "
TEXT 24 172 " VIDEO :           -voir catalogue IDVO "
TEXT 30 117 ""
TEXT 30 143 ""
TEXT 30 169 ""
TEXT 30 195 ""
TEXT 30 221 "RESEAUX :  -INTERNET   -http://hyperreal.com"
TEXT 30 247 "\t\\t\            -http://www.techno.net"
TEXT 30 273 " \t\\t\            -http://techno.stanford.edu"
TEXT 30 299 "\t\\t\            -http://www.nirvanet.fr"
TEXT 30 325 "\t\\t\            -http://cafenet.jovenet.fr/~cybernews\t\\t\\t\           "
TEXT 30 351 "                 \t\                                     -http://www.france-techno.fr"
TEXT 30 377 "\t\\t\            -http://www.subspace.net\t\           "
TEXT 30 403 ""
TEXT 30 429 "\t\            -3615  CODA, FG, RAVE"
TEXT 30 455 "\t\          \t\\t\\t\\t\\t\\t\"
TEXT 352 117 ""
MARK complement
SELECT complement
BUTTON position 589 469 630 511  GOTO SOMMAIRETXT.C
PAUSE -1
END

EVENT CATALOGUED.PIXELS
PICTURE "RAM:CATALOGUED.PIXELS"
MARK replace 5 1 2 3 4 22 6 7 8 9 10 11 12 13 14 15 16 17 18 19 22 21 20 23 24 25 26 27 28 29 30 31
SELECT replace 5 1 2 3 4 22 6 7 8 9 10 11 12 13 14 15 16 17 18 19 22 21 20 23 24 25 26 27 28 29 30 31
BUTTON position 601 220 629 250  GOTO IDVOcassettes1
PAUSE -1
GOTO IDVOcassettes1
END

EVENT IDVOcassettes1
PICTURE "RAM:PAGE.CONTINUE"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT FuturaB.font 17 16
COLOR 1 0 0 0 0 14 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline italics remap center kerning
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 88 30 "    CASSETTES VIDEO D' IMAGES DE SYNTHESE SUR MIX DJ"
FONT Compact.font 15 16
ATTRIBUTES kerning
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 48 " "
TEXT 30 66 "X-MIX-2 : Mix de Laurent Garnier\t\\t\\t\140 F.  (Pal)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 84 "(K. Larkin, Dave Angel, Deepside ...)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 102 "X-MIX-3 : Mix de Richie Hawtin & JohnAcquaviva\t\\t\140 F.  (Pal)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 120 "(L. Garnier, Plastikman, Speedy J. ...)"
FONT Compact.font 15 16
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 138 "X-MIX-4 : Mix de Dave Angel\t\\t\\t\140 F.  (Pal) "
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 156 "(K. Larkin, Chez Damier, P. Hazel ...)"
FONT Compact.font 15 16
ATTRIBUTES kerning
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 174 "3 LUX : Techno vidéo mix\t\\t\\t\\t\140 F.  (Pal)"
TEXT 30 192 "3 LUX-2 : Techno-Trance vidéo mix\t\\t\\t\140 F.  (Pal)"
TEXT 30 210 "3 LUX-3 : A journey through ambience\t\\t\\t\140 F.  (Pal)"
ATTRIBUTES remap kerning
TEXT 30 228 "V-FORM  \"\AFTERS\"\ : Mix de Laurent Garnier\t\\t\\t\130 F.  (P/S)"
ATTRIBUTES kerning
TEXT 30 246 "ZONE 4  \"\DREAM TV\"\\t\\t\\t\\t\130 F.  (Secam)"
TEXT 30 264 "THUNDERDOME  8  \"\THE TOUR\"\\t\\t\\t\100 F.  (Pal)"
TEXT 30 282 "COMPILATION VIDEO  KK RECORDS\t\\t\\t\150 F.  (Pal)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 300 "(P.W.O.G., Kode IV ...)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 318 "MOTION BYTE \"\HYPNOTIC TRANCE\"\\t\\t\\t\140 F.  (Secam)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 336 "(Total eclipse, T.I.P., Hallucinogen ...)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 354 "LOVE IS THE MESSAGE : Mix de Dj Kid Paul\t\\t\\t\140 F.  (Pal)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 372 "(Film sur la Love Parade 94-Jaydee, Speedy J."
TEXT 30 388 " Felix da Housecat ...)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 404 "GAIA PARTY\t\\t\\t\\t\140 F.  (P/S)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 422 "(Visuels + images video de GAIA 6 - Trance Goa)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 438 "THE MIND'S EYE/BEYOND/THE GATE\t\\t\\t\140 F.  (Pal)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 456 "(3 K7 des plus belles images de synthese)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 472 "EAT STATIC   \"\INTRUSION\"\\t\\t\\t\\t\130 F.  (Pal)"
TEXT 30 490 ""
TEXT 30 508 ""
FONT Data.font 24 14
STYLE 0 3 4 3 6 1 1 14 1 1 13 0 2 5 1 0 4 4 3
TEXT 605 384 ""
MARK complement
SELECT complement
BUTTON position 595 475 625 505  GOTO IDVOcassettes2
PAUSE -1
END

EVENT IDVOcassettes2
PICTURE "RAM:PAGE.EXIT"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 15 16
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "VIRTUAL  KINGDOM  \t\\t\\t\\t\   90 F."
FONT FuturaB.font 17 16
ATTRIBUTES kerning
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 48 "(Jeff Mills + Laurent Garnier - L' Anfer 95)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 66 "FUTURIA 96 \t\\t\\t\\t\  140 F."
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 84 "(Carl Cox, Stephanovitch, Manu le Malin, ...)               \
                                                                         \
                            "
FONT Data.font 24 14
STYLE 0 3 4 3 6 1 1 14 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 102 "                                                            \
                                    \t\\t\       DIVERS"
FONT FuturaB.font 17 16
ATTRIBUTES underline italics center kerning
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 274 118 "    DIVERS"
FONT Compact.font 15 16
ATTRIBUTES kerning
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 136 ""
TEXT 30 154 "LOCALIZER 1.0\t\\t\\t\\t\ 280 F."
FONT FuturaB.font 17 16
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 172 "(Livre consacre a la culture techno- 300 pages couleurs "
ATTRIBUTES kerning
TEXT 30 188 "anglais/allemand)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 204 "TOBIAS RICHTER \"\SPACE WARS\"\\t\\t\\t\    90 F. (P/S)"
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 222 "(Film d'animation 3D  realise sur Amiga)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 238 "FRACTAL UNIVERSE\t\\t\\t\\t\    50 F. "
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 256 "(CD ROM dedie aux fractales)"
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 272 "BEAUTY OF CHAOS\t\\t\\t\\t\   120 F."
FONT FuturaB.font 17 16
STYLE 0 3 4 3 6 1 1 17 1 1 13 0 2 5 1 0 4 4 3
TEXT 30 290 "(CD ROM dedie aux fractales) "
FONT Compact.font 15 16
STYLE 0 3 4 3 6 1 1 14 2 1 13 0 2 5 1 0 4 4 3
TEXT 30 306 ""
TEXT 30 324 ""
ATTRIBUTES center kerning
TEXT 305 246 "\t\"
TEXT 319 264 ""
TEXT 319 282 ""
TEXT 319 300 ""
TEXT 319 318 ""
TEXT 319 336 ""
TEXT 319 354 ""
TEXT 319 372 ""
TEXT 319 390 ""
TEXT 84 408 "Règlement par chèque à l'ordre d' I.D.V.O. - Frais de port recommandé : 30 F."
TEXT 116 426 "   I.D.V.O.   BP 574  21 015  DIJON cedex (France)  Fax : 80.59.05.21.    "
ATTRIBUTES remap kerning
TEXT 80 32 ""
ATTRIBUTES kerning
TEXT 135 108 ""
MARK complement
SELECT complement
BUTTON position 589 468 631 511  GOTO SOMMAIRETXT.C
PAUSE -1
END

EVENT CREDITS
PICTURE "RAM:PAGE.EXIT"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 25 31
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap left kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 32 30 "\t\\t\              C R E D I T S"
FONT Compact.font 19 24
ATTRIBUTES center kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 319 56 ""
COLOR 1 0 1 2 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline center kerning
TEXT 62 82 "CONCEPTION/REALISATION/ANIMATIONS/FREEFLYERS  :"
FONT Data.font 40 24
COLOR 1 0 0 2 0 0 1 0 0 1 1 2 2 2 1
ATTRIBUTES 3D center kerning
STYLE 0 3 4 3 3 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 230 108 "CH.  DEZERT"
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES center kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 319 134 ""
ATTRIBUTES underline center kerning
TEXT 235 160 "MODULE  TECHNO :"
FONT Data.font 40 24
COLOR 1 0 0 2 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES 3D center kerning
STYLE 0 3 4 3 3 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 75 186 "Transual  Flight (!RAMP!ATOMIX)"
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES center kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 319 212 ""
ATTRIBUTES underline center kerning
TEXT 241 238 "MODULE  HOUSE :"
ATTRIBUTES kerning
TEXT 30 186 ""
ATTRIBUTES center kerning
TEXT 319 212 ""
TEXT 319 238 ""
FONT Data.font 40 24
COLOR 1 0 0 2 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES 3D center kerning
STYLE 0 3 4 3 3 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 1 264 "Let the record spin (RANDALL/SUBURBAN)"
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES center kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 319 290 ""
ATTRIBUTES underline center kerning
TEXT 191 316 "MODULE INTRO & AMBIENT :"
FONT Data.font 40 24
COLOR 1 0 0 2 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES 3D center kerning
STYLE 0 3 4 3 3 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 14 342 "Coming from the sky/Warm night'n stars"
TEXT 198 368 "(Johan ALPMAR)"
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES center kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 319 394 ""
ATTRIBUTES underline center kerning
TEXT 226 420 "MODULE  HARDCORE "
FONT Data.font 40 24
ATTRIBUTES center kerning
TEXT 183 446 "BRAIN-DEAD (DAX) "
FONT Compact.font 19 24
TEXT 319 472 " "
TEXT 319 498 ""
TEXT 319 524 ""
FONT Data.font 40 24
TEXT 1 550 "Let the record spin (RANDALL/SUBURBAN)"
FONT Compact.font 19 24
TEXT 319 576 ""
TEXT 319 602 ""
TEXT 319 628 ""
FONT Data.font 40 24
TEXT 319 654 ""
TEXT 319 680 ""
TEXT 319 706 ""
TEXT 319 732 ""
FONT Compact.font 19 24
TEXT 319 758 ""
TEXT 319 784 ""
FONT Compact.font 25 31
ATTRIBUTES remap left kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXT 32 436 ""
MARK complement
SELECT complement
BUTTON position 589 469 631 511  GOTO SOMMAIRETXT.C
PAUSE -1
END

EVENT THECREAMDJs
PICTURE "RAM:THECREAMDJs"
MARK complement
SELECT complement
BUTTON position 666 501 694 530  GOTO THECREAMliveacts
PAUSE -1
END

EVENT THECREAMliveacts
PICTURE "RAM:THECREAMliveacts"
MARK complement
SELECT complement
BUTTON position 665 501 694 530  GOTO THECREAMliveacts2
PAUSE -1
END

EVENT THECREAMliveacts2
PICTURE "RAM:THECREAMliveacts2"
WIPE superimpose speed 3
MARK complement
SELECT complement
BUTTON position 666 501 694 530  GOTO THECREAMlabels
PAUSE -1
END

EVENT THECREAMlabels
PICTURE "RAM:THECREAMlabels"
MARK complement
SELECT replace 0 1 2 3 4 5 6 7
BUTTON position 658 488 699 530  GOTO SOMMAIRETXT.C
PAUSE -1
END

EVENT SOMMAIREORIGINESok
PICTURE "RAM:SOMMAIREORIGINESok"
BUTTON position 601 39 698 64  GOTO SOMMAIRE
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
BUTTON position 95 51 326 139  GOTO POPHISTORY1
BUTTON position 210 176 443 265  GOTO ROOTS
BUTTON position 329 300 559 390  GOTO NEBULEUSE
BUTTON position 446 424 679 515  GOTO hotspots.1
PAUSE -1
END

EVENT ROOTS
PICTURE "RAM:PAGE.CONTINUE"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 25 31
COLOR 1 0 0 0 0 14 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap center kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 283 30 "ROOTS"
FONT Compact.font 19 24
ATTRIBUTES underline left kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 32 63 ""
ATTRIBUTES left kerning
TEXT 32 89 "BLUES: Muddy Waters, Bo Diddley, BB King ..."
TEXT 32 115 ""
TEXT 32 141 "RYTHM'n'BLUES:  Aretha Franklin, Wilson Pickett ..."
TEXT 32 167 ""
TEXT 32 193 "JAZZ: Miles Davis, John Coltrane, Charlie Parker ..."
TEXT 32 219 ""
TEXT 32 245 "SOUL: James Brown, Curtis Mayfield, Marvin Gaye"
TEXT 32 271 "               Diana Ross, Temptations ..."
TEXT 32 297 ""
TEXT 32 323 "FUNK: Prince, Isley Brothers, Parliament, War, Maceo"
TEXT 32 349 "               Parker ..."
TEXT 32 375 ""
TEXT 32 401 "DISCO: Donna Summer, Bohannon, Sylvester, Chic ..."
TEXT 32 427 ""
TEXT 32 453 ""
TEXT 32 479 " "
TEXT 32 505 ""
TEXT 32 531 ""
TEXT 32 557 ""
TEXT 32 583 ""
TEXT 32 609 ""
TEXT 32 635 ""
TEXT 32 661 ""
TEXT 32 687 ""
TEXT 32 713 ""
TEXT 32 739 ""
TEXT 32 765 ""
TEXT 32 791 " "
TEXT 32 817 ""
MARK complement
SELECT complement
BUTTON position 595 476 624 506  GOTO ROOTS1
PAUSE -1
END

EVENT ROOTS1
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 25 31
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap center kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 233 30 "ROOTS  (part. 2)"
FONT Compact.font 19 24
ATTRIBUTES underline left kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 32 63 ""
ATTRIBUTES left kerning
TEXT 32 89 ""
TEXT 32 115 "MUSIQUE CONCRETE & ELECTROACOUSTIQUE: Stockhausen"
TEXT 32 141 "Pierre Henry, Pierre Schaeffer, Luc Ferrari ... "
TEXT 32 167 ""
TEXT 32 193 "MUSIQUE REPETITIVE: Terry Riley, Steve Reich, Philip Glass"
TEXT 32 219 "La Monte Young ..."
TEXT 32 245 ""
TEXT 32 271 "MUSIQUE PLANANTE: Klaus Schulze, Tangerine Dream, Heldon"
TEXT 32 297 "Pink Floyd ..."
TEXT 32 323 ""
TEXT 32 349 "ROCK ELECTRONIQUE: Kraftwerk, Can, Brian Eno, Neu, Devo..."
TEXT 32 375 ""
TEXT 32 401 ""
TEXT 32 427 ""
TEXT 32 453 ""
FONT Compact.font 25 31
ATTRIBUTES underline remap center kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXT 319 280 ""
MARK complement
SELECT complement
BUTTON position 595 477 624 506  GOTO ROOTS3
PAUSE -1
END

EVENT ROOTS3
PICTURE "RAM:PAGE.EXIT"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 25 31
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES underline remap center kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 233 30 "ROOTS  (part. 3)"
FONT Compact.font 19 24
ATTRIBUTES underline left kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 32 63 ""
ATTRIBUTES left kerning
TEXT 32 89 ""
TEXT 32 115 ""
TEXT 32 141 "COLD WAVE & MUSIQUE INDUSTRIELLE: Cabaret Voltaire, DAF"
TEXT 32 167 "Throbbing Gristle, Psychic TV, Chris&Cosey, Coil, Front 242"
TEXT 32 193 "Suicide, Residents ..."
TEXT 32 219 ""
TEXT 32 245 "TECHNO-POP: Human League, Yello, Yellow Magic Orchestra"
TEXT 32 271 "Ruichi Sakamoto, Dépêche Mode, New Order, Art of noise"
TEXT 32 297 "Soft Cell, Orchestral Manoeuvre  in the dark ...  "
TEXT 32 323 ""
FONT Compact.font 25 31
ATTRIBUTES underline remap center kerning
STYLE 0 3 4 3 6 1 1 27 4 1 13 0 2 5 1 0 4 4 3
TEXT 319 280 ""
MARK complement
SELECT complement
BUTTON position 589 469 631 511  GOTO SOMMAIREORIGINESok
PAUSE -1
END

EVENT hotspots.1
PICTURE "RAM:hotspots.1"
MARK complement
SELECT complement
BUTTON position 664 495 690 522  GOTO hotspots.2
PAUSE -1
END

EVENT hotspots.2
PICTURE "RAM:hotspots.2"
WIPE flow north speed 8
MARK complement
SELECT complement
BUTTON position 653 487 692 526  GOTO SOMMAIREORIGINESok
PAUSE -1
END

EVENT NEBULEUSE
PICTURE "RAM:NEBULEUSE"
MARK replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 127 126 129 128 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 127
SELECT replace 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 127 126 129 128 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
BUTTON position 314 457 357 502  GOTO SOMMAIREORIGINESok
PAUSE -1
END

EVENT POPHISTORY1
PICTURE "RAM:POPHISTORY1"
MARK replace 1 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15
SELECT replace 1 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15
BUTTON position 657 490 685 521  GOTO POPHISTORY2
PAUSE -1
END

EVENT POPHISTORY2
PICTURE "RAM:POPHISTORY2"
WIPE cube south speed 4
MARK replace 1 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15
SELECT replace 1 0 2 3 4 5 6 7 8 9 10 11 12 13 14 15
BUTTON position 650 484 691 527  GOTO SOMMAIREORIGINESok
PAUSE -1
END

EVENT CODA.1
PICTURE "RAM:PAGE.CONTINUE"
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Data.font 40 24
COLOR 1 7 7 7 7 14 1 7 0 1 2 3 5 4 1
ATTRIBUTES underline remap center kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 231 30 "CODA  93-96"
FONT Data.font 43 26
ATTRIBUTES underline left kerning
STYLE 0 3 4 3 6 1 1 24 2 1 13 0 2 5 1 0 4 4 3
TEXT 32 58 ""
FONT Compact.font 19 24
ATTRIBUTES left kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXT 32 86 ""
TEXT 32 112 "N° 1 (Mai 93) : cyberpunk, histoire de France des raves"
TEXT 32 138 "Laurent Garnier, J. Pacman, Sonic, R&S, home studio :"
TEXT 32 164 "TB 303, Nice & Cannes ..."
TEXT 32 190 ""
TEXT 32 216 "N° 2 : Mayday, Universe, Liza'n'Eliaz, Cosmic Baby, Alakiri"
TEXT 32 242 "Warp, tékhné, studio : histoire, Toulouse ..."
TEXT 32 268 ""
TEXT 32 294 "N° 3 : visuels, logomania, Aphex twin, Spiral tribe, G. la"
TEXT 32 320 "tortue, Harthouse, studio : Gem, bonnet ..."
TEXT 32 346 ""
TEXT 32 372 "N° 4 : techno la maudite, rave en kit, Rotterdam recds"
TEXT 32 398 "Loren X, lexique, Laurent Garnier, studio : JD 800, flyers ..."
TEXT 32 424 ""
TEXT 32 450 ""
TEXT 32 476 ""
MARK complement
SELECT complement
BUTTON position 596 475 623 506  GOTO CODA.2
PAUSE -1
END

EVENT CODA.2
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 3
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 7 7 7 7 0 1 7 0 1 2 3 5 4 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "N° 5 : retro 93, province, ambient, electro/techno, Manu le"
ATTRIBUTES kerning
TEXT 30 56 "malin, Robert Owens, Fnac music, PFXC, studio : monitoring"
TEXT 30 82 " + histoire, feutrines ..."
TEXT 30 108 ""
TEXT 30 134 "N° 6 : Manchester, Rising High, Frankie Knuckles, Jam &"
TEXT 30 160 "Spoon, Carl Cox, Scan X, Jack, Ettore Sottsas, studio :"
TEXT 30 186 "sampling, piercing ..."
TEXT 30 212 ""
TEXT 30 238 "N° 7 : Californie, Damon Wild, Eddy De Clercq, new age, DJ"
TEXT 30 264 "français, D.Jax Upbeats, multimedia, Dj Pierre, FSOL, Steve"
TEXT 30 290 "Hillage, Masters at works, cyberculture, Daft Punk, Ron"
TEXT 30 316 "Trent, Chez Damier, studio : bass station ..."
TEXT 30 342 ""
TEXT 30 368 "N° 8 : Energy 94, ambient night, Solar Quest, Shazz, V. form"
TEXT 30 394 "Hardcore, Tonio, Carl Craig, John Acquaviva, Robert Leiner"
TEXT 30 420 "Prodigy, Steve Miller, studio : techno machines ..."
MARK complement
SELECT complement
BUTTON position 596 476 623 506  GOTO CODA.3
PAUSE -1
END

EVENT CODA.3
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 5
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 7 7 7 7 0 1 7 0 1 2 3 5 4 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "N° 9 : Universe, Yello, Pacman, Lenny Dee, Insektor, GPR"
ATTRIBUTES kerning
TEXT 30 56 "Lumukanda, Zen Paradox, Sven Väth, Jungle, CC & the music"
TEXT 30 82 "factory, Tribal, Australie, studio : techno machines ..."
TEXT 30 108 ""
TEXT 30 134 "N° 10 : Goa, Acid Kirk, Oliver Bondzio, Orbital, Ralphee Dee"
TEXT 30 160 "Electric Indigo, Chris Burden, réalité virtuelle, Boy Georges"
TEXT 30 186 "Martha Wash, studio : Quasar ..."
TEXT 30 212 ""
TEXT 30 238 "N° 11 : Internet, Nova Zembla, KK, Armando, Laurent Hô, Moby"
TEXT 30 264 "Imagina, Thomas P. Heckmann, Moody Boyz, Pete Namlook"
TEXT 30 290 "Leftfield, studio : synthèse du son, Sound Factory ..."
TEXT 30 316 ""
TEXT 30 342 "N° 12 : la Suède, Jeff Mills, EM:T, Woody Mc Bride, Mister C."
TEXT 30 368 "Pierre Huyghe, Luke Slater, Strictly Rythm, studio :"
TEXT 30 394 "synthèse ..."
MARK complement
SELECT complement
BUTTON position 596 476 623 505  GOTO CODA.4
PAUSE -1
END

EVENT CODA.4
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 5
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 7 7 7 7 0 1 7 0 1 2 3 5 4 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "N° 13 : Cajmere, Universe, Mayday, Trip Hop, Josh Wink"
ATTRIBUTES kerning
TEXT 30 56 "Matthew Barney, Ludovic Navarre, Tim Taylor, New"
TEXT 30 82 "Electronica, studio : MS 404 ..."
TEXT 30 108 ""
TEXT 30 134 "N° 14 : Morpheus, Trip hop, Kenny Larkin, Fuse, Thrussel"
TEXT 30 160 "D.Jack, Joi Cardwell, Derrick May, Radikal Groov, H.P."
TEXT 30 186 "Jakobsen, Stephanovitch, Junior boy's own, technorama :"
TEXT 30 212 "J. Pacman ..."
TEXT 30 238 ""
TEXT 30 264 "N° 15 : Jungle, Black & Brown, Dub, Amsterdam, raves d' été"
TEXT 30 290 "Money Mark, Who's next, Stacey Pullen, Nu Groove, New York"
TEXT 30 316 "C&C Rogers, Bernard Joisten, technorama : Pacman/Remix 16"
TEXT 30 342 ""
TEXT 30 368 "N° 16 : Chemical Brothers, Dj Sneak, Coa, Cristian Vogel, latin"
TEXT 30 394 "house, PWOG, Dub, Dj Pure, deep groove, Azuli, technorama :"
TEXT 30 420 "Daft Punk ... "
TEXT 30 446 ""
MARK complement
SELECT complement
BUTTON position 596 476 623 505  GOTO CODA.5
PAUSE -1
END

EVENT CODA.5
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 5
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 7 7 7 7 0 1 7 0 1 2 3 5 4 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "N° 17 : Slam/Soma, Aquarium, Steve Cop, biodrogues, New"
ATTRIBUTES kerning
TEXT 30 56 "York, François Kevorkian, Dave Angel, Baby Ford, Ken Ishii"
TEXT 30 82 "tecnorama : LFO ..."
TEXT 30 108 ""
TEXT 30 134 "N° 18 : Dj Gregory/Dan Curtin, Chicago, Mandrax, Cup of tea"
TEXT 30 160 "hardcore, Graeme Park, Tantra, The Advent, Micronauts"
TEXT 30 186 "Scanner, Transmusicales, technorama : CD sampling ..."
TEXT 30 212 ""
TEXT 30 238 "N° 19 : Gerideau, Manny Ward, Woob, Digidub, electro, Riou"
TEXT 30 264 "Kevin Saunderson, Larry Heard, Dj Hell, Emmanuel Top, Miloch"
TEXT 30 290 "LFO, biennale de Lyon, technorama : T.P. Heckmann ..."
TEXT 30 316 ""
TEXT 30 342 "N° 20 : Djul'z, electric London, U.Star, Nuphonic, Grant Nelson"
TEXT 30 368 "System 7, Dave Clark, Paul Johnson, Ninja tunes, Space time"
TEXT 30 394 "continuum, Man with no name, Hallucinogen, Terry Hunter"
TEXT 30 420 "Traffic, Oliver Boscovitch, Midem, technorama : Scan X ..."
TEXT 30 446 ""
MARK complement
SELECT complement
BUTTON position 596 476 623 505  GOTO CODA.6
PAUSE -1
END

EVENT CODA.6
PICTURE "RAM:PAGE.CONTINUE"
WIPE superimpose speed 5
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 30 "N° 21 : Polaris, Front 242, Nova Nova, Brian Transeau, Jeff"
ATTRIBUTES kerning
TEXT 30 56 "Mills, Indus, Frankie Feliciano, Leftfield, Lil'Louis, Photek"
TEXT 30 82 "Underworld, techno & internet, Gary Hill, technorama :"
TEXT 30 108 "home studio ..."
TEXT 30 134 ""
TEXT 30 160 "N° 22 : referendum, Carl Cox, Japon, Robert Owens, drum &"
TEXT 30 186 "bass heros, Elegia, Dimitri from Paris, Lunatic Asylum, Sir."
TEXT 30 212 "cus, F. Gonzalez-Torres, technorama : Technossomy, S2000"
TEXT 30 238 ""
TEXT 30 264 "N° 23 : Sarajevo Underground, Lady B, Junior Vasquez,  Meat"
TEXT 30 290 "Beat Manifesto, Terry Mulan, Motorbass, Fila Brazilia/Pork"
TEXT 30 316 "Designers Republic, Reload, Orbital, Marshall Jefferson"
TEXT 30 342 "technorama : U-Bald, MC303, Remix 16 ..."
TEXT 30 368 ""
TEXT 30 394 "N° 24 : Love Parade, Erik Rug, Eddie flashing Fowles, Sonar"
TEXT 30 420 "Daft Punk, Alton Miller, XMF, David Holmes, Steve Silk Hurley"
TEXT 30 446 "Cajmere, Asley Beedle, Italie, technorama : sonorisation ... "
MARK complement
SELECT complement
BUTTON position 596 476 623 505  GOTO CODA.7
PAUSE -1
END

EVENT CODA.7
PICTURE "RAM:PAGE.EXIT"
WIPE superimpose speed 5
TABS 100 200 300 400 500
MARGINS on 32 607
FONT Compact.font 19 24
COLOR 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
ATTRIBUTES remap kerning
STYLE 0 3 4 3 6 1 1 22 2 1 13 0 2 5 1 0 4 4 3
TEXTWIPE dump speed 1
TEXT 30 368 ""
ATTRIBUTES kerning
TEXT 30 289 ""
TEXT 30 370 ""
TEXT 30 108 ""
TEXT 30 134 ""
TEXT 30 160 ""
TEXT 30 186 ""
TEXT 30 212 ""
TEXT 30 238 ""
TEXT 30 264 ""
TEXT 30 290 ""
TEXT 30 316 ""
TEXT 30 342 ""
TEXT 30 368 ""
TEXT 30 30 "Hors-série N° 1 : dance historik, presse et techno, criminal"
TEXT 30 56 "justice, circulaires, Rhône Alpes, contagion répressive"
TEXT 30 82 "points de vue et entretiens, lexique ..."
TEXT 30 108 ""
TEXT 30 134 "Hors-série N°2 : Douste-Blazy, 6 ans de techno, dance"
TEXT 30 160 "machinerie, tubes story, label histoire, techno esthétique"
TEXT 30 186 "FG, global techno, internet, Christian Perrot, ethno-techno."
MARK complement
SELECT complement
BUTTON position 596 476 623 505  GOTO SOMMAIRETXT.C
PAUSE -1
END
