From megalith!errors@uunet.uu.net Sun Oct 23 23:44:02 1994
Received: from relay3.UU.NET by toadflax.cs.ucdavis.edu (4.1/UCD.CS.2.6)
	id AA16297; Sun, 23 Oct 94 23:42:13 PDT
Received: from uucp7.UU.NET by relay3.UU.NET with SMTP 
	id QQxmys21803; Mon, 24 Oct 1994 02:42:10 -0400
Received: from megalith.UUCP by uucp7.UU.NET with UUCP/RMAIL
        ; Mon, 24 Oct 1994 02:42:30 -0400
Received: by megalith.miami.fl.us (wUUCP 1.10)
	  id <2p6h@megalith.miami.fl.us>; Mon, 24 Oct 94 01:31:36 -0400
Sender: CSAA@megalith.miami.fl.us
Errors-To: errors@megalith.miami.fl.us
Warnings-To: errors@megalith.miami.fl.us
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 8bit
X-Newsgatesoftware: Amiga Newsgate V1.6
Reply-To: rrogers@cs.washington.edu (Richard Rogers)
Message-Number: 964
Newsgroups: comp.sys.amiga.announce
X-Newssoftware: CSAA NMS 1.2
Message-Id: <overlord.2ogc@megalith.miami.fl.us>
Date: Mon, 24 Oct 1994 01:31:34 -0400
From: rrogers@cs.washington.edu (Richard Rogers) (CSAA)
To: announce@cs.ucdavis.edu (CSAA-Submissions)
Subject: (CSAA) Script v1.1
Status: RO

TITLE

   SCRIPT:

VERSION 

   1.1

AUTHOR

   Richard Rogers
   rrogers@cs.washington.edu

DESCRIPTION

   SCRIPT: is an AmigaDOS device that gives the Amiga the 
   functionality of the "script" command in UNIX.  SCRIPT: is
   actually more general, in that it can echo the I/O passing 
   through any AmigaDOS device to any other device, including 
   itself.

   For those of you not familiar with UNIX, the script command 
   causes the "screen" input and output to be saved to a file 
   (which is frequently then printed).  This is useful for 
   things like demonstrating to your professor that your program
   works correctly.  It's like a terminal program's capture or
   buffer feature, only for the shell.

   On the Amiga, the command shell can use any device (usually CON:).
   Some Workbench programs allow you to specify the device they use
   via the WINDOW tooltype.  Setting WINDOW to SCRIPT: allows you
   to script programs run from Workbench.  SCRIPT: captures the I/O
   going through any device and echos it to any other device. 
   Echoing to the SCRIPT: device itself allows you to echo the I/O
   to several devices at once.  

FEATURES

   -Standard AmigaDOS device driver
   -Works with Workbench & Shell/CLI

SPECIAL REQUIREMENTS

   -AmigaDOS 1.2 or later

HOST

   Aminet FTP sites (ftp.wustl.edu, etc.)

DIRECTORY

   /pub/aminet/util/cli

FILE NAME

   script.lha    5329 bytes

DISTRIBUTION

   Freely distributable.  Send donations to the author to encourage 
   futher development.

--
Read all administrative posts before putting your post up.  Mailing list:
announce-request@cs.ucdavis.edu.  Comments to CSAA@megalith.miami.fl.us.
MAIL ALL COMP.SYS.AMIGA.ANNOUNCE ANNOUNCEMENTS TO announce@cs.ucdavis.edu.

============================================================================
This is part of a mailing list gateway maintained by Carlos Amezaga.  Bugs
& comments to CSAA@megalith.miami.fl.us.  Subscribes, UnSubcribes, help and
faq requests should be sent to announce-request@cs.ucdavis.edu.



