From m90rca@tdb.uu.se Fri Oct 22 09:03:15 1993
Received: from bellatrix.tdb.uu.se by toadflax.cs.ucdavis.edu (4.1/UCD.CS.2.4)
	id AA14170; Fri, 22 Oct 93 09:03:11 PDT
Received: from hassaleh.tdb.uu.se (hassaleh-le1) by bellatrix.tdb.uu.se (5.0/SMI-SVR4)
	id AA05962; Fri, 22 Oct 93 17:03:17 +0100
From: m90rca@tdb.uu.se (Richard Carlsson)
Message-Id: <9310221603.AA05962@bellatrix.tdb.uu.se>
Subject: REVISED Fast Z80 emulation package for 680x0 processors
To: announce@cs.ucdavis.edu
Date: Fri, 22 Oct 1993 17:05:35 +0100 (MET)
X-Mailer: ELM [version 2.4 PL22]
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
Content-Length: 1337      
Status: RO

TITLE

     Zilog Z80 CPU emulator package for the Motorola M68000 family

VERSION

     0.99b

AUTHOR

     Richard Carlsson (m90rca@tdb.uu.se)

DESCRIPTION

     A general and flexible subroutine package for fast emulation of a Z80
     on any 680x0-based machine. It has a simple interface, and stubs for
     calling from C are included.
     The package could be used to emulate a Z80 in any environment (CP/M,
     ZX80/81, ZX Spectrum, ... ). The purpose of the package is to serve
     as the kernel of any such emulator; only the environment is left for
     the user to implement.
     The package has been developed in cooperation with Peter McGavin, the
     author of the best known ZX Spectrum emulator for the Amiga. All you
     who have written to Peter asking him to make a more general package
     of his emulator - this is the thing for you.

NEW FEATURES

     First release (beta testing version). Only some minor bugs remain.
     Try it out and tell me if you want any modifications or new features.

HOST NAME

     Aminet (wuarchive.wustl.edu and its mirrors)

DIRECTORY

     /pub/amiga/misc/emu

FILE NAME

     fastZ80_099b.lha

PRICE

     Free.

DISTRIBUTABILITY

    The archive and its contents are freely distributable.
    See documentation for details.

    The package is (c) 1993 Richard Carlsson


