Listob field:256 label:"Name" width:28 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:257 label:"System_Affected" width:50 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:258 label:"Properties" width:74 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:259 label:"Description" width:30 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:262 label:"Toxicity" width:40 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:264 label:"Dosage" width:50 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:265 label:"Botanical_Name" width:50 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:260 label:"Origin" width:30 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:261 label:"Notes" width:50 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Listob field:263 label:"Type" width:15 tcolor:1 bcolor:5 font:courier.font size:13 style:0 just:0 lspace:0 ltype:4 lcol:0 tcolor:1 bcolor:14 font:courier.font size:13 style:0 just:0 lspace:1 ltype:4 lcol:0 
Box g:0 196 572 140 areacolor:3 textg:0 0 483 139 textcolor:1 backcolor:0 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:RECESS frameg:4 2 564 136 
Field g:120 280 361 19 ftype:Input fieldname:264 areacolor:25 textg:6 3 350 13 textcolor:1 backcolor:25 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 350 13 
Box g:0 4 572 32 areacolor:5 textg:0 0 483 31 textcolor:1 backcolor:0 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:RECESS frameg:4 2 564 28 
Field g:444 12 123 17 ftype:Popup fieldname:263 areacolor:0 textg:4 2 105 13 textcolor:1 backcolor:0 drawmode:1 textfont:courier.font size:13 style:0 just:0 iconname:TwistIcon:DefaultPopUp icong:111 6 8 5 frametype:RECESS frameg:4 2 115 13 15 -4 8 18 "Herb" 8 32 "Vitamin" 8 46 "Mineral" 8 60 "Animal" 8 74 "Amino Acid" 8 88 "FruitVeggy" 8 102 "Enzyme" 8 116 "Other" 
Box g:0 92 572 104 areacolor:4 textg:0 0 483 103 textcolor:1 backcolor:0 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:RECESS frameg:4 2 564 100 
Box g:0 68 572 24 areacolor:9 textg:0 0 483 23 textcolor:1 backcolor:0 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:RECESS frameg:4 2 564 20 
Label g:8 16 28 13 fieldname:256 areacolor:-1 textg:0 0 28 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Name"
Field g:120 12 256 19 ftype:Input fieldname:256 areacolor:2 textg:6 3 245 13 textcolor:1 backcolor:2 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 245 13 
Label g:8 72 105 13 fieldname:256 areacolor:-1 textg:0 0 105 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"System_Affected"
Field g:120 72 361 19 ftype:Input fieldname:257 areacolor:2 textg:6 3 350 13 textcolor:1 backcolor:2 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 350 13 
Label g:8 100 70 13 fieldname:256 areacolor:-1 textg:0 0 70 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Properties"
Field g:120 96 428 92 ftype:Editor fieldname:258 areacolor:15 textg:6 3 417 86 textcolor:1 backcolor:15 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 417 86 
Label g:8 208 77 13 fieldname:256 areacolor:-1 textg:0 0 77 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Description"
Field g:120 204 292 19 ftype:Input fieldname:259 areacolor:25 textg:6 3 281 13 textcolor:1 backcolor:25 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 281 13 
Label g:12 232 42 13 fieldname:256 areacolor:-1 textg:0 0 42 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Origin"
Field g:120 228 221 19 ftype:Input fieldname:260 areacolor:25 textg:6 3 210 13 textcolor:1 backcolor:25 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 210 13 
Label g:12 316 35 13 fieldname:256 areacolor:-1 textg:0 0 35 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Notes"
Field g:120 312 396 19 ftype:Input fieldname:261 areacolor:25 textg:6 3 385 13 textcolor:1 backcolor:25 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 385 13 
Label g:12 256 56 13 fieldname:256 areacolor:-1 textg:0 0 56 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Toxicity"
Field g:120 252 291 19 ftype:Input fieldname:262 areacolor:25 textg:6 3 280 13 textcolor:1 backcolor:25 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 280 13 
Text g:404 8 35 13 areacolor:-1 textg:0 0 35 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Type-"
Label g:12 284 44 13 fieldname:256 areacolor:-1 textg:0 0 44 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Dosage"
Box g:0 36 572 32 areacolor:13 textg:0 0 483 31 textcolor:1 backcolor:0 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:RECESS frameg:4 2 564 28 
Field g:120 44 432 19 ftype:Input fieldname:265 areacolor:2 textg:6 3 421 13 textcolor:1 backcolor:2 drawmode:1 textfont:courier.font size:13 style:0 just:0 frametype:BLINE frameg:6 3 421 13 
Label g:8 44 98 13 fieldname:256 areacolor:-1 textg:0 0 98 13 textcolor:1 backcolor:5 drawmode:1 textfont:courier.font size:13 style:0 just:0 text:"Botanical Name"
