From megalith!errors@uunet.uu.net Thu Jun  9 03:39:51 1994
Received: from relay3.UU.NET by toadflax.cs.ucdavis.edu (4.1/UCD.CS.2.5)
	id AA17593; Thu, 9 Jun 94 03:33:23 PDT
Received: from uucp5.uu.net by relay3.UU.NET with SMTP 
	(rama) id QQwtnm09873; Thu, 9 Jun 1994 06:31:28 -0400
Received: from megalith.UUCP by uucp5.uu.net with UUCP/RMAIL
        ; Thu, 9 Jun 1994 06:31:30 -0400
Received: by megalith.miami.fl.us (V1.16.20/w5, Dec 29 1993, 21:22:55)
	  id <1ma7@megalith.miami.fl.us>; Thu, 9 Jun 94 02:47:08 EDT -0400
Sender: overlord@megalith.miami.fl.us
Errors-To: errors@megalith.miami.fl.us
Warnings-To: errors@megalith.miami.fl.us
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 8bit
Reply-To: dsears@efn.org (Douglas Sears)
Message-Number: 851
Newsgroups: comp.sys.amiga.announce
X-Newssoftware: CSAA NMS 1.2
Message-Id: <overlord.1m84@megalith.miami.fl.us>
Date: Thu, 09 Jun 1994 02:47:06 -0400 (EDT)
From: Douglas Sears <dsears@efn.org> (CSAA)
To: announce@cs.ucdavis.edu (CSAA-Submissions)
Subject: (CSAA) ReSource disassembler Release 6
Status: RO

TITLE

     ReSource

VERSION

     Release 6

DESCRIPTION

     ReSource is an intelligent disassembler for Amiga programmers. It is
     very fast and fully interactive, and allows you to "do it your way".
     There are plenty of options, and decisions are not forced on you.

     ReSource is aimed at those who need to disassemble large programs
     into source files that will reassemble and run correctly. For a
     disassembler to achieve this, it must be able to produce totally
     bug-free output. Furthermore, it must be able to produce high-quality
     output with the minimum of effort from the user. ReSource achieves
     both of these objectives, albeit at the cost of large memory usage.

     Since ReSource can get its input from a file, track, or memory, and
     output all or part to any of these, it is more a general purpose tool
     than just a disassembler. It can be used to browse through files,
     without bothering to save anything, just to find out what is inside.

     Because ReSource understands AmigaDOS(tm) and the Amiga OS, you can
     concentrate on the task at hand, and not expend effort on trying to
     look up or remember details better left to a computer.

NEW FEATURES

     ReSource is now compatible with Intuition, and provides a public
     screen.  You may now run your favorite utilities on ReSource's
     screen. New startup options include a Screen Mode requester. The
     displayable character set now includes all printable characters.

     We moved the hundreds of Symbols menu items into a scrollable Symbol
     Requester, and the built-in symbol bases now completely reflect the
     39.108 Include.i release.  Support for multiple symbols in the same
     base that resolve to the same value (unions, etc.) has been added.

     Macros, environmental Options, and the old, confusing search items
     have all been moved from the menus to their own requester windows.

     Release 6 disassembles the entire MC68000 family:  All CPUs
     through 68040; the 68881, 68882, and 68040 FPUs; and the 68851, 68030,
     and 68040 MMUs.  Full support of floating point code has been added.

     Online help includes all the new features, and you can now use the help
     system to get information about all the OS V39 System Library functions.

     The "zap" function has a new requester window that includes data type
     and size gadgets, and a mini-assembler for code modifications.

SPECIAL REQUIREMENTS

     ReSource runs on an Amiga 500, 1000, 2000, 3000, or 4000 and now
     requires AmigaOS V2.0.  Because of the size of the support files for
     Release 6, it will no longer be useful on a system with 1 megabyte
     of ram.  We suggest at least 2 megabytes of ram to do useful work.
     For the same reason, we no longer support installation to floppy disk.

PRICE

     US$150 + shipping.  Ground shipping is included in the U.S. and
     Canada.  Others please call.

COMPANY

     The Puzzle Factory, Inc.    Voice: (800) 828-9952 - Orders only
     P.O. Box 986                       (503) 935-3709 - Questions/support
     Veneta, OR 97487              BBS: (503) 935-7883
     USA                      Internet: jlavin@efn.org

        In Europe, contact:
     Helios Software             Voice: +(623) 554828
     163 Huthwaite Road
     Sutton-in-Ashfield
     Nottinghamshire NG17 2HB
     UK

DISTRIBUTABILITY

     Commercial software.  Copyright 1994 The Puzzle Factory, Inc.

OTHER

     ReSource is a trademark of The Puzzle Factory, Inc.
     Amiga is a registered trademark of Commodore-Amiga, Inc.

SUBMITTER

     Doug Sears <dsears@efn.org>.  I work with The Puzzle
     Factory, and submitted this at their request.
--
Read all administrative posts before putting your post up.  Mailing list:
announce-request@cs.ucdavis.edu.  Comments to CSAA@megalith.miami.fl.us.
MAIL ALL COMP.SYS.AMIGA.ANNOUNCE ANNOUNCEMENTS TO announce@cs.ucdavis.edu.

============================================================================
This is part of a mailing list gateway maintained by Carlos Amezaga.  Bugs
& comments to CSAA@megalith.miami.fl.us.  Subscribes, UnSubcribes, help and
faq requests should be sent to announce-request@cs.ucdavis.edu.



